import { evaluateFormula } from "@/lib/formula-engine";

export type BaseSectorId =
  | "mecanica"
  | "eletrica"
  | "hidraulica"
  | "producao"
  | "pneumatica"
  | "estrutural"
  | "termodinamica"
  | "instrumentacao"
  | "automacao"
  | "manutencao"
  | "logistica"
  | "qualidade"
  | "planejamento"
  | "energia"
  | "elevadores_mistura_90";

export type SectorId = BaseSectorId | (string & {});

export type Difficulty = "Basica" | "Intermediaria" | "Avancada";
export type UsageLevel = "Baixo" | "Moderado" | "Alto" | "Critico";
export type FormulaStatus = "rascunho" | "em_revisao" | "validada" | "aprovada" | "arquivada";

export interface Sector {
  id: SectorId;
  name: string;
  description: string;
  formulas: number;
  activeCalculations: number;
  health: number;
  trend: string;
  usageLevel: UsageLevel;
  color: string;
  iconName: string;
}

export interface FormulaVariable {
  name: string;
  label: string;
  unit: string;
  placeholder?: string;
}

export interface Formula {
  id: string;
  name: string;
  sectorId: SectorId;
  sector: string;
  expression: string;
  resultUnit: string;
  description: string;
  variables: FormulaVariable[];
  difficulty: Difficulty;
  usageCount: number;
  example: string;
  simpleExplanation: string;
  tags: string[];
  status: FormulaStatus;
  createdBy: string;
  approvedBy?: string;
  createdAt: string;
  approvedAt?: string;
  version: number;
  technicalNotes?: string;
  isCustom?: boolean;
}

export interface CalculationRecord {
  id: number;
  formulaId: string;
  formula: string;
  sector: string;
  sectorId: SectorId;
  values: Record<string, string>;
  result: string;
  unit: string;
  formulaStatus: FormulaStatus;
  status: "Validado" | "Rascunho" | "Revisao";
  operator: string;
  date: string;
  isoDate: string;
}

type BaseSector = Omit<Sector, "formulas">;

type FormulaSeed = Omit<
  Formula,
  "sector" | "difficulty" | "usageCount" | "status" | "createdBy" | "approvedBy" | "createdAt" | "approvedAt" | "version"
> & {
  difficulty?: Difficulty;
  usageCount?: number;
  status?: FormulaStatus;
  createdBy?: string;
  approvedBy?: string;
  createdAt?: string;
  approvedAt?: string;
  version?: number;
};

const variable = (name: string, label: string, unit: string, placeholder: string): FormulaVariable => ({
  name,
  label,
  unit,
  placeholder,
});

const baseSectors: BaseSector[] = [
  {
    id: "mecanica",
    name: "Mecanica",
    description: "Torque, esforcos, potencia rotativa, materiais e dimensionamento de conjuntos mecanicos.",
    activeCalculations: 145,
    health: 92,
    trend: "+12%",
    usageLevel: "Critico",
    color: "#ff6a00",
    iconName: "Wrench",
  },
  {
    id: "eletrica",
    name: "Eletrica",
    description: "Potencia, motores, quedas de tensao, consumo, demanda e correcao de fator de potencia.",
    activeCalculations: 132,
    health: 90,
    trend: "+9%",
    usageLevel: "Critico",
    color: "#38bdf8",
    iconName: "Zap",
  },
  {
    id: "hidraulica",
    name: "Hidraulica",
    description: "Vazao, pressao, perda de carga, bombas, Reynolds e tanques industriais.",
    activeCalculations: 116,
    health: 87,
    trend: "+7%",
    usageLevel: "Alto",
    color: "#22d3ee",
    iconName: "Droplets",
  },
  {
    id: "producao",
    name: "Producao",
    description: "OEE, takt time, capacidade, produtividade, refugos e cadencia de linhas.",
    activeCalculations: 128,
    health: 95,
    trend: "+16%",
    usageLevel: "Critico",
    color: "#f59e0b",
    iconName: "BarChart3",
  },
  {
    id: "pneumatica",
    name: "Pneumatica",
    description: "Cilindros, consumo de ar, compressores, velocidade e perdas em linhas pneumaticas.",
    activeCalculations: 74,
    health: 82,
    trend: "+6%",
    usageLevel: "Moderado",
    color: "#60a5fa",
    iconName: "Gauge",
  },
  {
    id: "estrutural",
    name: "Estrutural",
    description: "Flexao, tensoes, flambagem, deflexao, cisalhamento e fator de seguranca.",
    activeCalculations: 86,
    health: 88,
    trend: "+5%",
    usageLevel: "Alto",
    color: "#a3e635",
    iconName: "Building2",
  },
  {
    id: "termodinamica",
    name: "Termodinamica",
    description: "Calor, gases, rendimento, COP, trocadores e potencia termica de processos.",
    activeCalculations: 64,
    health: 84,
    trend: "+4%",
    usageLevel: "Moderado",
    color: "#ef4444",
    iconName: "Thermometer",
  },
  {
    id: "instrumentacao",
    name: "Instrumentacao",
    description: "Sinais 4-20 mA, span, erro, resolucao, incerteza e rangeabilidade de instrumentos.",
    activeCalculations: 79,
    health: 91,
    trend: "+10%",
    usageLevel: "Alto",
    color: "#c084fc",
    iconName: "SlidersHorizontal",
  },
  {
    id: "automacao",
    name: "Automacao",
    description: "PLC, redes industriais, tempos de resposta, disponibilidade, buffers e I/O.",
    activeCalculations: 93,
    health: 89,
    trend: "+11%",
    usageLevel: "Alto",
    color: "#14b8a6",
    iconName: "Cpu",
  },
  {
    id: "manutencao",
    name: "Manutencao",
    description: "MTBF, MTTR, disponibilidade, confiabilidade, custos e planejamento de OS.",
    activeCalculations: 101,
    health: 86,
    trend: "+8%",
    usageLevel: "Alto",
    color: "#fb7185",
    iconName: "ShieldCheck",
  },
  {
    id: "logistica",
    name: "Logistica industrial",
    description: "Estoque, lead time, ocupacao, picking, nivel de servico e lote economico.",
    activeCalculations: 58,
    health: 80,
    trend: "+3%",
    usageLevel: "Moderado",
    color: "#f97316",
    iconName: "Truck",
  },
  {
    id: "qualidade",
    name: "Qualidade",
    description: "Cp, Cpk, PPM, DPU, DPMO, rendimento, retrabalho e indicadores de processo.",
    activeCalculations: 88,
    health: 94,
    trend: "+13%",
    usageLevel: "Alto",
    color: "#10b981",
    iconName: "BadgeCheck",
  },
  {
    id: "planejamento",
    name: "Planejamento",
    description: "Carga maquina, ocupacao, prazo, EVM, necessidade de material e estoque de seguranca.",
    activeCalculations: 69,
    health: 85,
    trend: "+6%",
    usageLevel: "Moderado",
    color: "#facc15",
    iconName: "CalendarClock",
  },
  {
    id: "energia",
    name: "Energia",
    description: "Fator de carga, custo, demanda, eficiencia energetica, emissao e retorno de projetos.",
    activeCalculations: 97,
    health: 90,
    trend: "+14%",
    usageLevel: "Alto",
    color: "#84cc16",
    iconName: "BatteryCharging",
  },
  {
    id: "elevadores_mistura_90",
    name: "Elevadores e Mistura 90",
    description:
      "Setor técnico voltado aos cálculos de elevadores industriais, capacidade de transporte, tensões, correias, eixos, potência, redutores, acoplamentos e rolamentos, baseado no documento técnico Calculos Equipamentos Mistura 90.",
    activeCalculations: 42,
    health: 91,
    trend: "+18%",
    usageLevel: "Critico",
    color: "#ff6a00",
    iconName: "Factory",
  },
];

const sectorNameById = Object.fromEntries(baseSectors.map((sector) => [sector.id, sector.name])) as Record<SectorId, string>;

const formulaSeeds: FormulaSeed[] = [
  {
    id: "torque",
    name: "Torque de Aperto",
    sectorId: "mecanica",
    expression: "T = F * r",
    resultUnit: "N.m",
    description: "Calcula o torque aplicado por uma forca tangencial em um braco de alavanca.",
    variables: [variable("F", "Forca aplicada", "N", "150"), variable("r", "Raio ou braco", "m", "0.30")],
    difficulty: "Basica",
    usageCount: 145,
    example: "F = 150 N e r = 0.30 m resultam em 45 N.m.",
    simpleExplanation: "Quanto maior a forca ou o braco, maior o torque transmitido.",
    tags: ["torque", "aperto", "eixo"],
  },
  {
    id: "potencia-rotativa",
    name: "Potencia Rotativa",
    sectorId: "mecanica",
    expression: "P = T * omega",
    resultUnit: "W",
    description: "Determina a potencia mecanica entregue por um eixo em rotacao.",
    variables: [variable("T", "Torque", "N.m", "80"), variable("omega", "Velocidade angular", "rad/s", "31.4")],
    usageCount: 118,
    example: "T = 80 N.m e omega = 31.4 rad/s geram 2512 W.",
    simpleExplanation: "Potencia rotativa combina o torque disponivel com a velocidade de giro.",
    tags: ["potencia", "eixo", "rotacao"],
  },
  {
    id: "forca-atrito",
    name: "Forca de Atrito",
    sectorId: "mecanica",
    expression: "Fa = mu * N",
    resultUnit: "N",
    description: "Estima a resistencia por atrito entre duas superficies em contato.",
    variables: [variable("mu", "Coeficiente de atrito", "", "0.25"), variable("N", "Forca normal", "N", "1200")],
    difficulty: "Basica",
    usageCount: 76,
    example: "mu = 0.25 e N = 1200 N geram 300 N.",
    simpleExplanation: "O atrito cresce conforme a carga normal e o coeficiente da superficie.",
    tags: ["atrito", "carga", "deslizamento"],
  },
  {
    id: "trabalho-mecanico",
    name: "Trabalho Mecanico",
    sectorId: "mecanica",
    expression: "W = F * d",
    resultUnit: "J",
    description: "Calcula energia transferida quando uma forca desloca uma carga.",
    variables: [variable("F", "Forca", "N", "500"), variable("d", "Deslocamento", "m", "2.4")],
    difficulty: "Basica",
    usageCount: 61,
    example: "F = 500 N e d = 2.4 m resultam em 1200 J.",
    simpleExplanation: "Trabalho e forca multiplicada pelo deslocamento na mesma direcao.",
    tags: ["energia", "deslocamento"],
  },
  {
    id: "velocidade-linear-eixo",
    name: "Velocidade Linear no Diametro",
    sectorId: "mecanica",
    expression: "v = pi * D * n / 60",
    resultUnit: "m/s",
    description: "Converte rotacao e diametro em velocidade periferica.",
    variables: [variable("D", "Diametro", "m", "0.18"), variable("n", "Rotacao", "rpm", "1750")],
    usageCount: 84,
    example: "D = 0.18 m e n = 1750 rpm geram 16.49 m/s.",
    simpleExplanation: "A borda de um disco percorre uma circunferencia a cada volta.",
    tags: ["rpm", "velocidade", "polia"],
  },
  {
    id: "tensao-normal",
    name: "Tensao Normal",
    sectorId: "mecanica",
    expression: "sigma = F / A",
    resultUnit: "Pa",
    description: "Calcula a tensao axial media aplicada em uma secao.",
    variables: [variable("F", "Forca axial", "N", "25000"), variable("A", "Area resistente", "m2", "0.0008")],
    usageCount: 92,
    example: "F = 25000 N e A = 0.0008 m2 geram 31.25 MPa.",
    simpleExplanation: "A mesma forca gera mais tensao quando a area resistente e menor.",
    tags: ["tensao", "materiais", "axial"],
  },
  {
    id: "deformacao-linear",
    name: "Deformacao Linear",
    sectorId: "mecanica",
    expression: "epsilon = delta / L",
    resultUnit: "",
    description: "Calcula deformacao relativa a partir do alongamento medido.",
    variables: [variable("delta", "Alongamento", "mm", "0.35"), variable("L", "Comprimento inicial", "mm", "500")],
    usageCount: 47,
    example: "delta = 0.35 mm e L = 500 mm resultam em 0.0007.",
    simpleExplanation: "Mostra quanto a peca alongou em relacao ao tamanho original.",
    tags: ["deformacao", "ensaio", "materiais"],
  },
  {
    id: "potencia-elevacao",
    name: "Potencia de Elevacao",
    sectorId: "mecanica",
    expression: "P = m * g * h / t",
    resultUnit: "W",
    description: "Estima potencia para elevar uma massa em determinado tempo.",
    variables: [
      variable("m", "Massa", "kg", "250"),
      variable("g", "Gravidade", "m/s2", "9.81"),
      variable("h", "Altura", "m", "3"),
      variable("t", "Tempo", "s", "12"),
    ],
    usageCount: 66,
    example: "m = 250 kg, h = 3 m e t = 12 s geram cerca de 613 W.",
    simpleExplanation: "Elevar mais massa, mais alto ou mais rapido exige mais potencia.",
    tags: ["elevacao", "talha", "potencia"],
  },
  {
    id: "potencia-ativa-monofasica",
    name: "Potencia Ativa Monofasica",
    sectorId: "eletrica",
    expression: "P = V * I * FP",
    resultUnit: "W",
    description: "Calcula potencia ativa em circuito monofasico considerando fator de potencia.",
    variables: [variable("V", "Tensao", "V", "220"), variable("I", "Corrente", "A", "18"), variable("FP", "Fator de potencia", "", "0.86")],
    difficulty: "Basica",
    usageCount: 132,
    example: "V = 220 V, I = 18 A e FP = 0.86 geram 3405.6 W.",
    simpleExplanation: "A potencia util depende da tensao, corrente e eficiencia angular da carga.",
    tags: ["potencia", "monofasico", "fp"],
  },
  {
    id: "potencia-trifasica",
    name: "Potencia Ativa Trifasica",
    sectorId: "eletrica",
    expression: "P = sqrt(3) * V * I * FP",
    resultUnit: "W",
    description: "Calcula potencia ativa em circuito trifasico equilibrado.",
    variables: [variable("V", "Tensao linha-linha", "V", "380"), variable("I", "Corrente", "A", "32"), variable("FP", "Fator de potencia", "", "0.88")],
    usageCount: 121,
    example: "V = 380 V, I = 32 A e FP = 0.88 geram 18533 W.",
    simpleExplanation: "Em trifasico, a potencia total inclui o fator sqrt(3).",
    tags: ["trifasico", "motor", "potencia"],
  },
  {
    id: "queda-tensao-monofasica",
    name: "Queda de Tensao Monofasica",
    sectorId: "eletrica",
    expression: "dV = 2 * I * R * L",
    resultUnit: "V",
    description: "Estima queda de tensao em cabo monofasico com ida e retorno.",
    variables: [variable("I", "Corrente", "A", "25"), variable("R", "Resistencia por metro", "ohm/m", "0.019"), variable("L", "Comprimento", "m", "50")],
    usageCount: 120,
    example: "I = 25 A, R = 0.019 ohm/m e L = 50 m geram 47.5 V.",
    simpleExplanation: "Cabos longos e correntes altas aumentam a perda de tensao.",
    tags: ["cabos", "queda", "instalacao"],
  },
  {
    id: "resistencia-condutor",
    name: "Resistencia de Condutor",
    sectorId: "eletrica",
    expression: "R = rho * L / A",
    resultUnit: "ohm",
    description: "Calcula resistencia eletrica a partir de resistividade, comprimento e area.",
    variables: [variable("rho", "Resistividade", "ohm.mm2/m", "0.0172"), variable("L", "Comprimento", "m", "80"), variable("A", "Area", "mm2", "10")],
    usageCount: 95,
    example: "rho = 0.0172, L = 80 m e A = 10 mm2 geram 0.1376 ohm.",
    simpleExplanation: "Condutores mais longos resistem mais; secoes maiores resistem menos.",
    tags: ["condutor", "resistencia", "cabo"],
  },
  {
    id: "energia-consumo",
    name: "Energia Consumida",
    sectorId: "eletrica",
    expression: "E = P * t / 1000",
    resultUnit: "kWh",
    description: "Converte potencia e tempo de uso em consumo energetico.",
    variables: [variable("P", "Potencia", "W", "7500"), variable("t", "Tempo", "h", "6")],
    difficulty: "Basica",
    usageCount: 109,
    example: "P = 7500 W por 6 h consome 45 kWh.",
    simpleExplanation: "Energia e a potencia acumulada ao longo do tempo.",
    tags: ["energia", "consumo", "kwh"],
  },
  {
    id: "corrente-motor-trifasico",
    name: "Corrente de Motor Trifasico",
    sectorId: "eletrica",
    expression: "I = P / (sqrt(3) * V * FP * eta)",
    resultUnit: "A",
    description: "Estima corrente absorvida por motor trifasico.",
    variables: [
      variable("P", "Potencia", "W", "15000"),
      variable("V", "Tensao", "V", "380"),
      variable("FP", "Fator de potencia", "", "0.86"),
      variable("eta", "Rendimento", "", "0.91"),
    ],
    usageCount: 117,
    example: "P = 15000 W em 380 V gera cerca de 29.2 A.",
    simpleExplanation: "A corrente cresce quando potencia aumenta ou rendimento/FP caem.",
    tags: ["motor", "corrente", "trifasico"],
  },
  {
    id: "fator-demanda",
    name: "Fator de Demanda",
    sectorId: "eletrica",
    expression: "FD = Pmax / Pinst",
    resultUnit: "",
    description: "Compara demanda maxima medida com potencia instalada.",
    variables: [variable("Pmax", "Demanda maxima", "kW", "180"), variable("Pinst", "Potencia instalada", "kW", "260")],
    usageCount: 54,
    example: "Pmax = 180 kW e Pinst = 260 kW geram FD = 0.69.",
    simpleExplanation: "Indica quanto da carga instalada realmente e usada no pico.",
    tags: ["demanda", "carga", "painel"],
  },
  {
    id: "reativo-correcao-fp",
    name: "Potencia Reativa para Correcao",
    sectorId: "eletrica",
    expression: "Qc = P * (tanPhi1 - tanPhi2)",
    resultUnit: "kVAr",
    description: "Estima banco capacitivo necessario para corrigir fator de potencia.",
    variables: [
      variable("P", "Potencia ativa", "kW", "120"),
      variable("tanPhi1", "Tangente inicial", "", "0.75"),
      variable("tanPhi2", "Tangente desejada", "", "0.33"),
    ],
    difficulty: "Avancada",
    usageCount: 58,
    example: "P = 120 kW, tanPhi1 = 0.75 e tanPhi2 = 0.33 pedem 50.4 kVAr.",
    simpleExplanation: "A diferenca de reativo define o tamanho aproximado do banco.",
    tags: ["reativo", "capacitor", "fp"],
  },
  {
    id: "vazao-bomba",
    name: "Vazao Volumetrica",
    sectorId: "hidraulica",
    expression: "Q = A * v",
    resultUnit: "m3/s",
    description: "Calcula vazao por area de passagem e velocidade do fluido.",
    variables: [variable("A", "Area da secao", "m2", "0.05"), variable("v", "Velocidade", "m/s", "2.5")],
    difficulty: "Basica",
    usageCount: 116,
    example: "A = 0.05 m2 e v = 2.5 m/s geram 0.125 m3/s.",
    simpleExplanation: "A vazao cresce quando o fluido passa mais rapido ou por area maior.",
    tags: ["vazao", "tubulacao", "bomba"],
  },
  {
    id: "pressao-hidraulica",
    name: "Pressao Hidraulica",
    sectorId: "hidraulica",
    expression: "p = F / A",
    resultUnit: "Pa",
    description: "Calcula pressao gerada por uma forca aplicada em area conhecida.",
    variables: [variable("F", "Forca", "N", "30000"), variable("A", "Area", "m2", "0.01")],
    usageCount: 90,
    example: "F = 30000 N e A = 0.01 m2 geram 3 MPa.",
    simpleExplanation: "A mesma forca gera maior pressao em uma area menor.",
    tags: ["pressao", "cilindro", "forca"],
  },
  {
    id: "potencia-hidraulica",
    name: "Potencia Hidraulica",
    sectorId: "hidraulica",
    expression: "P = p * Q / eta",
    resultUnit: "W",
    description: "Estima potencia requerida para entregar vazao sob pressao.",
    variables: [variable("p", "Pressao", "Pa", "3000000"), variable("Q", "Vazao", "m3/s", "0.004"), variable("eta", "Rendimento", "", "0.82")],
    usageCount: 82,
    example: "p = 3 MPa, Q = 0.004 m3/s e eta = 0.82 pedem 14634 W.",
    simpleExplanation: "Mais pressao ou vazao exige mais potencia da bomba.",
    tags: ["bomba", "potencia", "pressao"],
  },
  {
    id: "reynolds",
    name: "Numero de Reynolds",
    sectorId: "hidraulica",
    expression: "Re = rho * v * D / mu",
    resultUnit: "",
    description: "Classifica regime de escoamento em tubulacoes.",
    variables: [
      variable("rho", "Densidade", "kg/m3", "998"),
      variable("v", "Velocidade", "m/s", "1.8"),
      variable("D", "Diametro", "m", "0.08"),
      variable("mu", "Viscosidade dinamica", "Pa.s", "0.001"),
    ],
    difficulty: "Avancada",
    usageCount: 73,
    example: "Agua a 1.8 m/s em tubo de 80 mm gera Re acima de 140000.",
    simpleExplanation: "Reynolds ajuda a identificar se o escoamento e laminar ou turbulento.",
    tags: ["reynolds", "fluido", "turbulento"],
  },
  {
    id: "altura-manometrica",
    name: "Altura Manometrica por Pressao",
    sectorId: "hidraulica",
    expression: "H = p / (rho * g)",
    resultUnit: "m",
    description: "Converte pressao em coluna equivalente de fluido.",
    variables: [variable("p", "Pressao", "Pa", "250000"), variable("rho", "Densidade", "kg/m3", "998"), variable("g", "Gravidade", "m/s2", "9.81")],
    usageCount: 63,
    example: "p = 250 kPa equivale a cerca de 25.5 mca para agua.",
    simpleExplanation: "Mostra qual altura de coluna de fluido representa a pressao medida.",
    tags: ["mca", "pressao", "bomba"],
  },
  {
    id: "perda-carga-darcy",
    name: "Perda de Carga Darcy",
    sectorId: "hidraulica",
    expression: "hf = f * (L / D) * (v^2 / (2 * g))",
    resultUnit: "m",
    description: "Calcula perda de carga distribuida em tubulacao pelo metodo de Darcy-Weisbach.",
    variables: [
      variable("f", "Fator de atrito", "", "0.025"),
      variable("L", "Comprimento", "m", "80"),
      variable("D", "Diametro", "m", "0.1"),
      variable("v", "Velocidade", "m/s", "2.2"),
      variable("g", "Gravidade", "m/s2", "9.81"),
    ],
    difficulty: "Avancada",
    usageCount: 69,
    example: "Linha de 80 m com v = 2.2 m/s gera perda proxima de 4.9 m.",
    simpleExplanation: "Tubos longos, estreitos e velocidade alta aumentam a perda.",
    tags: ["perda", "darcy", "tubulacao"],
  },
  {
    id: "velocidade-tubulacao",
    name: "Velocidade em Tubulacao Circular",
    sectorId: "hidraulica",
    expression: "v = 4 * Q / (pi * D^2)",
    resultUnit: "m/s",
    description: "Calcula velocidade media a partir da vazao e diametro interno.",
    variables: [variable("Q", "Vazao", "m3/s", "0.012"), variable("D", "Diametro interno", "m", "0.1")],
    usageCount: 86,
    example: "Q = 0.012 m3/s e D = 0.1 m resultam em 1.53 m/s.",
    simpleExplanation: "Para a mesma vazao, tubos menores elevam a velocidade.",
    tags: ["velocidade", "diametro", "vazao"],
  },
  {
    id: "volume-tanque",
    name: "Volume de Tanque Prismático",
    sectorId: "hidraulica",
    expression: "V = A * h",
    resultUnit: "m3",
    description: "Calcula volume armazenado em tanque de area constante.",
    variables: [variable("A", "Area da base", "m2", "12"), variable("h", "Altura util", "m", "2.4")],
    difficulty: "Basica",
    usageCount: 55,
    example: "A = 12 m2 e h = 2.4 m resultam em 28.8 m3.",
    simpleExplanation: "Volume e a area da base multiplicada pela altura util.",
    tags: ["tanque", "volume", "armazenagem"],
  },
  {
    id: "oee",
    name: "OEE",
    sectorId: "producao",
    expression: "OEE = (D / 100) * (P / 100) * (Q / 100) * 100",
    resultUnit: "%",
    description: "Mede eficiencia global combinando disponibilidade, performance e qualidade.",
    variables: [variable("D", "Disponibilidade", "%", "92"), variable("P", "Performance", "%", "95"), variable("Q", "Qualidade", "%", "99.5")],
    usageCount: 128,
    example: "D = 92%, P = 95% e Q = 99.5% geram OEE de 87.03%.",
    simpleExplanation: "OEE mostra quanto do potencial produtivo virou producao boa.",
    tags: ["oee", "eficiencia", "linha"],
  },
  {
    id: "takt-time",
    name: "Takt Time",
    sectorId: "producao",
    expression: "TT = Tdisp / Demanda",
    resultUnit: "min/pc",
    description: "Define ritmo necessario para atender a demanda no tempo disponivel.",
    variables: [variable("Tdisp", "Tempo disponivel", "min", "420"), variable("Demanda", "Demanda do turno", "pc", "210")],
    usageCount: 103,
    example: "420 min para 210 pecas resultam em takt de 2 min/pc.",
    simpleExplanation: "Mostra a cada quanto tempo uma peca deve sair da linha.",
    tags: ["takt", "ritmo", "demanda"],
  },
  {
    id: "capacidade-producao",
    name: "Capacidade de Producao",
    sectorId: "producao",
    expression: "C = Tdisp / TC",
    resultUnit: "pc",
    description: "Estima quantidade produzivel com tempo disponivel e tempo de ciclo.",
    variables: [variable("Tdisp", "Tempo disponivel", "min", "480"), variable("TC", "Tempo de ciclo", "min/pc", "1.6")],
    usageCount: 97,
    example: "480 min com ciclo de 1.6 min/pc geram 300 pecas.",
    simpleExplanation: "Divide o tempo disponivel pelo tempo necessario por unidade.",
    tags: ["capacidade", "ciclo", "linha"],
  },
  {
    id: "produtividade-hora",
    name: "Produtividade por Hora",
    sectorId: "producao",
    expression: "Prod = Qp / H",
    resultUnit: "pc/h",
    description: "Calcula saida media por hora de trabalho.",
    variables: [variable("Qp", "Quantidade produzida", "pc", "840"), variable("H", "Horas trabalhadas", "h", "7")],
    difficulty: "Basica",
    usageCount: 88,
    example: "840 pecas em 7 h geram 120 pc/h.",
    simpleExplanation: "Mostra a cadencia media de producao por hora.",
    tags: ["produtividade", "hora", "saida"],
  },
  {
    id: "tempo-ciclo-medio",
    name: "Tempo de Ciclo Medio",
    sectorId: "producao",
    expression: "TC = Ttotal / N",
    resultUnit: "s/pc",
    description: "Calcula tempo medio por unidade produzida.",
    variables: [variable("Ttotal", "Tempo total", "s", "3600"), variable("N", "Unidades", "pc", "180")],
    usageCount: 79,
    example: "3600 s para 180 pecas geram 20 s/pc.",
    simpleExplanation: "Divide o tempo total pela quantidade produzida.",
    tags: ["ciclo", "tempo", "processo"],
  },
  {
    id: "taxa-refugo",
    name: "Taxa de Refugo",
    sectorId: "producao",
    expression: "R = Pe / Pt * 100",
    resultUnit: "%",
    description: "Calcula percentual de pecas refugadas em relacao ao total produzido.",
    variables: [variable("Pe", "Pecas refugadas", "pc", "18"), variable("Pt", "Pecas totais", "pc", "900")],
    usageCount: 70,
    example: "18 refugos em 900 pecas geram 2%.",
    simpleExplanation: "Mostra a parcela da producao perdida por defeitos.",
    tags: ["refugo", "perda", "qualidade"],
  },
  {
    id: "lead-time-producao",
    name: "Lead Time de Producao",
    sectorId: "producao",
    expression: "LT = Te + Tp + Tq + Tm",
    resultUnit: "h",
    description: "Soma esperas, processamento, fila de qualidade e movimentacao.",
    variables: [
      variable("Te", "Tempo de espera", "h", "4"),
      variable("Tp", "Tempo de processo", "h", "6"),
      variable("Tq", "Tempo de qualidade", "h", "1.5"),
      variable("Tm", "Tempo de movimentacao", "h", "0.5"),
    ],
    usageCount: 62,
    example: "4 + 6 + 1.5 + 0.5 resultam em 12 h.",
    simpleExplanation: "Lead time e o tempo total do item dentro do fluxo produtivo.",
    tags: ["lead time", "fluxo", "fila"],
  },
  {
    id: "eficiencia-mao-obra",
    name: "Eficiencia de Mao de Obra",
    sectorId: "producao",
    expression: "E = Hpad / Hreal * 100",
    resultUnit: "%",
    description: "Compara horas padrao produzidas com horas reais consumidas.",
    variables: [variable("Hpad", "Horas padrao", "h", "72"), variable("Hreal", "Horas reais", "h", "80")],
    usageCount: 59,
    example: "72 h padrao em 80 h reais geram 90%.",
    simpleExplanation: "Indica eficiencia do uso de mao de obra frente ao padrao.",
    tags: ["mao de obra", "eficiencia", "padrao"],
  },
  {
    id: "forca-cilindro-avanco",
    name: "Forca de Cilindro Pneumatico",
    sectorId: "pneumatica",
    expression: "F = p * A",
    resultUnit: "N",
    description: "Calcula forca teorica de avanco de um cilindro pneumatico.",
    variables: [variable("p", "Pressao", "Pa", "600000"), variable("A", "Area do pistao", "m2", "0.003")],
    difficulty: "Basica",
    usageCount: 74,
    example: "p = 600 kPa e A = 0.003 m2 geram 1800 N.",
    simpleExplanation: "Forca aumenta com a pressao e com a area do pistao.",
    tags: ["cilindro", "forca", "pneumatica"],
  },
  {
    id: "area-pistao",
    name: "Area de Pistao Circular",
    sectorId: "pneumatica",
    expression: "A = pi * D^2 / 4",
    resultUnit: "m2",
    description: "Calcula area util de pistao pelo diametro.",
    variables: [variable("D", "Diametro do pistao", "m", "0.063")],
    usageCount: 58,
    example: "D = 63 mm gera area de 0.00312 m2.",
    simpleExplanation: "O diametro define a area que recebe pressao.",
    tags: ["area", "cilindro", "pistao"],
  },
  {
    id: "consumo-ar-cilindro",
    name: "Consumo de Ar por Ciclo",
    sectorId: "pneumatica",
    expression: "Q = A * curso * ciclos * pAbs",
    resultUnit: "m3/min",
    description: "Estima consumo de ar corrigido pela pressao absoluta relativa.",
    variables: [
      variable("A", "Area do pistao", "m2", "0.003"),
      variable("curso", "Curso", "m", "0.25"),
      variable("ciclos", "Ciclos por minuto", "1/min", "30"),
      variable("pAbs", "Fator de pressao absoluta", "", "7"),
    ],
    usageCount: 52,
    example: "A = 0.003, curso = 0.25, 30 ciclos e fator 7 geram 0.1575 m3/min.",
    simpleExplanation: "Mais ciclos, curso maior ou pressao maior elevam consumo de ar.",
    tags: ["ar", "consumo", "cilindro"],
  },
  {
    id: "vazao-compressor",
    name: "Vazao de Compressor",
    sectorId: "pneumatica",
    expression: "Q = V / t",
    resultUnit: "m3/min",
    description: "Calcula vazao media a partir de volume entregue em certo tempo.",
    variables: [variable("V", "Volume", "m3", "3.6"), variable("t", "Tempo", "min", "2")],
    usageCount: 46,
    example: "3.6 m3 em 2 min resultam em 1.8 m3/min.",
    simpleExplanation: "Divide o volume entregue pelo tempo de enchimento.",
    tags: ["compressor", "vazao", "ar"],
  },
  {
    id: "forca-retorno-cilindro",
    name: "Forca de Retorno de Cilindro",
    sectorId: "pneumatica",
    expression: "F = p * (Ap - Ah)",
    resultUnit: "N",
    description: "Calcula forca de retorno considerando area da haste.",
    variables: [variable("p", "Pressao", "Pa", "600000"), variable("Ap", "Area do pistao", "m2", "0.003"), variable("Ah", "Area da haste", "m2", "0.0005")],
    usageCount: 44,
    example: "p = 600 kPa, Ap = 0.003 e Ah = 0.0005 geram 1500 N.",
    simpleExplanation: "No retorno, a haste reduz a area efetiva do cilindro.",
    tags: ["retorno", "haste", "forca"],
  },
  {
    id: "energia-pneumatica",
    name: "Energia Pneumatica Armazenada",
    sectorId: "pneumatica",
    expression: "E = p * V",
    resultUnit: "J",
    description: "Estima energia associada ao volume pressurizado.",
    variables: [variable("p", "Pressao", "Pa", "600000"), variable("V", "Volume", "m3", "0.02")],
    usageCount: 33,
    example: "p = 600 kPa e V = 0.02 m3 geram 12000 J.",
    simpleExplanation: "Volume pressurizado armazena energia proporcional a pressao.",
    tags: ["energia", "reservatorio", "ar"],
  },
  {
    id: "velocidade-cilindro",
    name: "Velocidade de Cilindro",
    sectorId: "pneumatica",
    expression: "v = Q / A",
    resultUnit: "m/s",
    description: "Calcula velocidade teorica pelo fluxo volumetrico e area.",
    variables: [variable("Q", "Vazao", "m3/s", "0.0012"), variable("A", "Area", "m2", "0.003")],
    usageCount: 49,
    example: "Q = 0.0012 m3/s e A = 0.003 m2 resultam em 0.4 m/s.",
    simpleExplanation: "Mais vazao aumenta a velocidade; area maior reduz.",
    tags: ["velocidade", "cilindro", "vazao"],
  },
  {
    id: "queda-pressao-pneumatica",
    name: "Queda de Pressao em Linha",
    sectorId: "pneumatica",
    expression: "dp = k * L * Q^2 / D^5",
    resultUnit: "Pa",
    description: "Modelo simplificado para perda de pressao em linha pneumatica.",
    variables: [
      variable("k", "Coeficiente da linha", "", "0.012"),
      variable("L", "Comprimento", "m", "30"),
      variable("Q", "Vazao", "m3/s", "0.02"),
      variable("D", "Diametro interno", "m", "0.025"),
    ],
    difficulty: "Avancada",
    usageCount: 31,
    example: "Com linha longa e diametro pequeno a perda cresce fortemente.",
    simpleExplanation: "O diametro domina a perda porque aparece elevado a quinta potencia.",
    tags: ["perda", "linha", "pressao"],
  },
  {
    id: "momento-viga-carga-central",
    name: "Momento Maximo em Viga Biapoiada",
    sectorId: "estrutural",
    expression: "M = F * L / 4",
    resultUnit: "N.m",
    description: "Calcula momento maximo para carga pontual no centro de viga biapoiada.",
    variables: [variable("F", "Carga central", "N", "12000"), variable("L", "Vao", "m", "4")],
    usageCount: 86,
    example: "F = 12000 N e L = 4 m geram 12000 N.m.",
    simpleExplanation: "A carga no centro gera o maior momento no meio do vao.",
    tags: ["viga", "momento", "flexao"],
  },
  {
    id: "tensao-flexao",
    name: "Tensao de Flexao",
    sectorId: "estrutural",
    expression: "sigma = M * c / I",
    resultUnit: "Pa",
    description: "Calcula tensao maxima por flexao em secao conhecida.",
    variables: [variable("M", "Momento fletor", "N.m", "12000"), variable("c", "Distancia ate fibra extrema", "m", "0.08"), variable("I", "Momento de inercia", "m4", "0.000004")],
    difficulty: "Avancada",
    usageCount: 82,
    example: "M = 12000, c = 0.08 e I = 4e-6 geram 240 MPa.",
    simpleExplanation: "Secoes com maior inercia reduzem a tensao de flexao.",
    tags: ["flexao", "tensao", "perfil"],
  },
  {
    id: "flambagem-euler",
    name: "Carga Critica de Flambagem",
    sectorId: "estrutural",
    expression: "Pcr = pi^2 * E * I / (K * L)^2",
    resultUnit: "N",
    description: "Calcula carga critica de Euler para coluna esbelta.",
    variables: [
      variable("E", "Modulo de elasticidade", "Pa", "200000000000"),
      variable("I", "Momento de inercia", "m4", "0.000008"),
      variable("K", "Fator de comprimento", "", "1"),
      variable("L", "Comprimento", "m", "3"),
    ],
    difficulty: "Avancada",
    usageCount: 64,
    example: "Coluna de 3 m com E = 200 GPa gera carga critica conforme sua inercia.",
    simpleExplanation: "Colunas longas e pouco rigidas flambam com cargas menores.",
    tags: ["flambagem", "coluna", "euler"],
  },
  {
    id: "deflexao-viga-central",
    name: "Deflexao de Viga com Carga Central",
    sectorId: "estrutural",
    expression: "delta = F * L^3 / (48 * E * I)",
    resultUnit: "m",
    description: "Calcula flecha maxima em viga biapoiada com carga central.",
    variables: [
      variable("F", "Carga", "N", "8000"),
      variable("L", "Vao", "m", "4"),
      variable("E", "Modulo de elasticidade", "Pa", "200000000000"),
      variable("I", "Momento de inercia", "m4", "0.000006"),
    ],
    difficulty: "Avancada",
    usageCount: 61,
    example: "A flecha cresce muito quando o vao aumenta.",
    simpleExplanation: "Deflexao depende fortemente do comprimento elevado ao cubo.",
    tags: ["flecha", "viga", "rigidez"],
  },
  {
    id: "cisalhamento-medio",
    name: "Tensao de Cisalhamento Media",
    sectorId: "estrutural",
    expression: "tau = V / A",
    resultUnit: "Pa",
    description: "Calcula tensao media de cisalhamento em uma area resistente.",
    variables: [variable("V", "Esforco cortante", "N", "15000"), variable("A", "Area resistente", "m2", "0.002")],
    usageCount: 55,
    example: "V = 15000 N e A = 0.002 m2 geram 7.5 MPa.",
    simpleExplanation: "Cisalhamento medio e o cortante dividido pela area.",
    tags: ["cisalhamento", "cortante", "tensao"],
  },
  {
    id: "fator-seguranca",
    name: "Fator de Seguranca",
    sectorId: "estrutural",
    expression: "FS = Sy / sigma",
    resultUnit: "",
    description: "Compara resistencia do material com tensao de trabalho.",
    variables: [variable("Sy", "Limite de escoamento", "Pa", "250000000"), variable("sigma", "Tensao atuante", "Pa", "90000000")],
    usageCount: 93,
    example: "Sy = 250 MPa e sigma = 90 MPa geram FS = 2.78.",
    simpleExplanation: "Quanto maior o FS, maior a margem antes do escoamento.",
    tags: ["seguranca", "material", "norma"],
  },
  {
    id: "von-mises",
    name: "Tensao Equivalente de Von Mises",
    sectorId: "estrutural",
    expression: "svm = sqrt(sigma^2 + 3 * tau^2)",
    resultUnit: "Pa",
    description: "Combina tensao normal e cisalhamento para avaliacao de escoamento.",
    variables: [variable("sigma", "Tensao normal", "Pa", "80000000"), variable("tau", "Tensao cisalhante", "Pa", "25000000")],
    difficulty: "Avancada",
    usageCount: 57,
    example: "sigma = 80 MPa e tau = 25 MPa geram tensao equivalente maior que 90 MPa.",
    simpleExplanation: "Von Mises transforma esforcos combinados em uma tensao comparavel ao material.",
    tags: ["von mises", "falha", "combinado"],
  },
  {
    id: "area-placa",
    name: "Area Resistente de Placa",
    sectorId: "estrutural",
    expression: "A = b * t",
    resultUnit: "m2",
    description: "Calcula area transversal simples de placa retangular.",
    variables: [variable("b", "Largura", "m", "0.12"), variable("t", "Espessura", "m", "0.01")],
    difficulty: "Basica",
    usageCount: 48,
    example: "b = 0.12 m e t = 0.01 m geram 0.0012 m2.",
    simpleExplanation: "A area resistente e largura multiplicada pela espessura.",
    tags: ["placa", "area", "secao"],
  },
  {
    id: "calor-sensivel",
    name: "Calor Sensivel",
    sectorId: "termodinamica",
    expression: "Q = m * cp * dT",
    resultUnit: "kJ",
    description: "Calcula energia para variar temperatura sem mudanca de fase.",
    variables: [variable("m", "Massa", "kg", "120"), variable("cp", "Calor especifico", "kJ/kg.K", "4.18"), variable("dT", "Variacao de temperatura", "K", "25")],
    usageCount: 64,
    example: "120 kg de agua aquecidos 25 K exigem 12540 kJ.",
    simpleExplanation: "Mais massa ou maior salto termico exige mais energia.",
    tags: ["calor", "aquecimento", "processo"],
  },
  {
    id: "calor-latente",
    name: "Calor Latente",
    sectorId: "termodinamica",
    expression: "Q = m * Lh",
    resultUnit: "kJ",
    description: "Calcula energia de mudanca de fase sem variar temperatura.",
    variables: [variable("m", "Massa", "kg", "20"), variable("Lh", "Calor latente", "kJ/kg", "2257")],
    usageCount: 46,
    example: "20 kg com Lh = 2257 kJ/kg pedem 45140 kJ.",
    simpleExplanation: "Mudanca de fase consome energia mesmo sem alterar temperatura.",
    tags: ["latente", "vapor", "fase"],
  },
  {
    id: "rendimento-termico",
    name: "Rendimento Termico",
    sectorId: "termodinamica",
    expression: "eta = W / Qin * 100",
    resultUnit: "%",
    description: "Calcula quanto do calor recebido virou trabalho util.",
    variables: [variable("W", "Trabalho util", "kJ", "320"), variable("Qin", "Calor fornecido", "kJ", "900")],
    usageCount: 53,
    example: "W = 320 kJ e Qin = 900 kJ geram 35.56%.",
    simpleExplanation: "Rendimento mostra a parte util da energia fornecida.",
    tags: ["rendimento", "energia", "ciclo"],
  },
  {
    id: "cop-refrigeracao",
    name: "COP de Refrigeracao",
    sectorId: "termodinamica",
    expression: "COP = Qfrio / W",
    resultUnit: "",
    description: "Calcula desempenho de sistema de refrigeracao.",
    variables: [variable("Qfrio", "Calor removido", "kW", "120"), variable("W", "Potencia consumida", "kW", "35")],
    usageCount: 58,
    example: "Qfrio = 120 kW e W = 35 kW geram COP = 3.43.",
    simpleExplanation: "COP indica quantas unidades de frio sao obtidas por unidade de potencia.",
    tags: ["cop", "refrigeracao", "chiller"],
  },
  {
    id: "gas-ideal",
    name: "Lei dos Gases Ideais",
    sectorId: "termodinamica",
    expression: "P = n * R * T / V",
    resultUnit: "Pa",
    description: "Relaciona pressao, volume, temperatura e quantidade de gas ideal.",
    variables: [
      variable("n", "Quantidade de materia", "mol", "12"),
      variable("R", "Constante dos gases", "J/mol.K", "8.314"),
      variable("T", "Temperatura", "K", "320"),
      variable("V", "Volume", "m3", "0.5"),
    ],
    usageCount: 41,
    example: "n = 12 mol, T = 320 K e V = 0.5 m3 geram 63836 Pa.",
    simpleExplanation: "Pressao cresce com temperatura e quantidade de gas, e cai com volume.",
    tags: ["gas", "pressao", "temperatura"],
  },
  {
    id: "vazao-massica",
    name: "Vazao Massica",
    sectorId: "termodinamica",
    expression: "mdot = rho * Q",
    resultUnit: "kg/s",
    description: "Converte vazao volumetrica em vazao massica.",
    variables: [variable("rho", "Densidade", "kg/m3", "1.2"), variable("Q", "Vazao volumetrica", "m3/s", "3.5")],
    usageCount: 49,
    example: "rho = 1.2 kg/m3 e Q = 3.5 m3/s geram 4.2 kg/s.",
    simpleExplanation: "Multiplica o volume que passa por segundo pela densidade do fluido.",
    tags: ["vazao", "massa", "ar"],
  },
  {
    id: "potencia-aquecimento",
    name: "Potencia de Aquecimento",
    sectorId: "termodinamica",
    expression: "P = m * cp * dT / t",
    resultUnit: "kW",
    description: "Calcula potencia termica media para aquecer uma massa em certo tempo.",
    variables: [
      variable("m", "Massa", "kg", "500"),
      variable("cp", "Calor especifico", "kJ/kg.K", "4.18"),
      variable("dT", "Variacao de temperatura", "K", "30"),
      variable("t", "Tempo", "s", "3600"),
    ],
    usageCount: 52,
    example: "500 kg de agua aquecidos 30 K em 1 h exigem cerca de 17.4 kW.",
    simpleExplanation: "A potencia cresce quando o aquecimento precisa ser mais rapido.",
    tags: ["aquecimento", "potencia", "resistencia"],
  },
  {
    id: "efetividade-trocador",
    name: "Efetividade de Trocador",
    sectorId: "termodinamica",
    expression: "epsilon = Qreal / Qmax * 100",
    resultUnit: "%",
    description: "Compara transferencia real com maxima possivel em trocador.",
    variables: [variable("Qreal", "Calor real", "kW", "180"), variable("Qmax", "Calor maximo", "kW", "240")],
    usageCount: 37,
    example: "Qreal = 180 kW e Qmax = 240 kW geram 75%.",
    simpleExplanation: "Mostra quao perto o trocador esta do limite teorico.",
    tags: ["trocador", "efetividade", "calor"],
  },
  {
    id: "span-instrumento",
    name: "Span de Instrumento",
    sectorId: "instrumentacao",
    expression: "S = URV - LRV",
    resultUnit: "",
    description: "Calcula amplitude de medicao entre limite superior e inferior.",
    variables: [variable("URV", "Valor superior", "un", "100"), variable("LRV", "Valor inferior", "un", "0")],
    difficulty: "Basica",
    usageCount: 79,
    example: "URV = 100 e LRV = 0 geram span de 100.",
    simpleExplanation: "Span e o tamanho da faixa calibrada do instrumento.",
    tags: ["span", "calibracao", "faixa"],
  },
  {
    id: "erro-percentual-instrumento",
    name: "Erro Percentual de Medicao",
    sectorId: "instrumentacao",
    expression: "E = (Medido - Real) / Span * 100",
    resultUnit: "%",
    description: "Calcula erro relativo da medicao em percentual do span.",
    variables: [variable("Medido", "Valor medido", "un", "52.4"), variable("Real", "Valor real", "un", "50"), variable("Span", "Span", "un", "100")],
    usageCount: 72,
    example: "Medido = 52.4, real = 50 e span = 100 geram 2.4%.",
    simpleExplanation: "Erro percentual ajuda a avaliar se o instrumento esta dentro da tolerancia.",
    tags: ["erro", "calibracao", "medicao"],
  },
  {
    id: "corrente-4-20",
    name: "Sinal 4-20 mA por PV",
    sectorId: "instrumentacao",
    expression: "I = 4 + 16 * (PV - LRV) / (URV - LRV)",
    resultUnit: "mA",
    description: "Converte valor de processo em corrente analogica 4-20 mA.",
    variables: [variable("PV", "Valor de processo", "un", "75"), variable("LRV", "Limite inferior", "un", "0"), variable("URV", "Limite superior", "un", "100")],
    usageCount: 77,
    example: "PV = 75 em faixa 0-100 gera 16 mA.",
    simpleExplanation: "4 mA representa o inicio da faixa e 20 mA o fim.",
    tags: ["4-20", "analogico", "transmissor"],
  },
  {
    id: "pv-por-corrente",
    name: "PV por Sinal 4-20 mA",
    sectorId: "instrumentacao",
    expression: "PV = LRV + (I - 4) * (URV - LRV) / 16",
    resultUnit: "un",
    description: "Converte corrente analogica 4-20 mA em valor de processo.",
    variables: [variable("I", "Corrente", "mA", "12"), variable("LRV", "Limite inferior", "un", "0"), variable("URV", "Limite superior", "un", "200")],
    usageCount: 75,
    example: "I = 12 mA em faixa 0-200 gera PV = 100.",
    simpleExplanation: "12 mA fica no meio da faixa entre 4 e 20 mA.",
    tags: ["4-20", "pv", "instrumento"],
  },
  {
    id: "resolucao-conversor",
    name: "Resolucao de Conversor",
    sectorId: "instrumentacao",
    expression: "Res = Span / (2^bits)",
    resultUnit: "un/bit",
    description: "Calcula menor incremento teorico por bit em conversor digital.",
    variables: [variable("Span", "Span de medicao", "un", "100"), variable("bits", "Bits do conversor", "bits", "12")],
    usageCount: 43,
    example: "Span 100 em 12 bits gera 0.0244 un/bit.",
    simpleExplanation: "Mais bits reduzem o tamanho de cada passo digital.",
    tags: ["resolucao", "adc", "bits"],
  },
  {
    id: "incerteza-combinada",
    name: "Incerteza Combinada",
    sectorId: "instrumentacao",
    expression: "Uc = sqrt(u1^2 + u2^2 + u3^2)",
    resultUnit: "un",
    description: "Combina componentes independentes de incerteza por soma quadratica.",
    variables: [variable("u1", "Incerteza 1", "un", "0.2"), variable("u2", "Incerteza 2", "un", "0.3"), variable("u3", "Incerteza 3", "un", "0.1")],
    difficulty: "Avancada",
    usageCount: 40,
    example: "0.2, 0.3 e 0.1 combinam para 0.374.",
    simpleExplanation: "Componentes independentes se combinam pela raiz da soma dos quadrados.",
    tags: ["incerteza", "calibracao", "metrologia"],
  },
  {
    id: "rangeabilidade",
    name: "Rangeabilidade",
    sectorId: "instrumentacao",
    expression: "R = Qmax / Qmin",
    resultUnit: ":1",
    description: "Calcula relacao entre maior e menor valor mensuravel com desempenho aceitavel.",
    variables: [variable("Qmax", "Vazao maxima", "un", "100"), variable("Qmin", "Vazao minima", "un", "5")],
    usageCount: 32,
    example: "Qmax = 100 e Qmin = 5 geram 20:1.",
    simpleExplanation: "Mostra a amplitude util de operacao do instrumento.",
    tags: ["range", "vazao", "instrumento"],
  },
  {
    id: "ganho-sensor",
    name: "Ganho de Sensor",
    sectorId: "instrumentacao",
    expression: "K = Sinal / PV",
    resultUnit: "sinal/un",
    description: "Calcula sensibilidade do sensor como sinal gerado por unidade medida.",
    variables: [variable("Sinal", "Sinal de saida", "mV", "120"), variable("PV", "Grandeza medida", "un", "30")],
    usageCount: 36,
    example: "120 mV para 30 unidades gera ganho 4 mV/un.",
    simpleExplanation: "Ganho alto significa que pequenas mudancas geram mais sinal.",
    tags: ["sensor", "ganho", "sensibilidade"],
  },
  {
    id: "carga-scan-plc",
    name: "Carga de Scan de PLC",
    sectorId: "automacao",
    expression: "L = Tscan / Tlim * 100",
    resultUnit: "%",
    description: "Compara tempo de scan atual com limite aceitavel do controle.",
    variables: [variable("Tscan", "Tempo de scan", "ms", "18"), variable("Tlim", "Limite de scan", "ms", "50")],
    usageCount: 93,
    example: "Tscan = 18 ms e Tlim = 50 ms geram 36%.",
    simpleExplanation: "Mostra quanto do limite de ciclo do PLC esta sendo usado.",
    tags: ["plc", "scan", "controle"],
  },
  {
    id: "throughput-rede-industrial",
    name: "Throughput de Rede Industrial",
    sectorId: "automacao",
    expression: "Th = Pacotes * Bytes * 8 / t",
    resultUnit: "bit/s",
    description: "Calcula taxa de dados trafegados em rede industrial.",
    variables: [variable("Pacotes", "Pacotes", "un", "12000"), variable("Bytes", "Bytes por pacote", "B", "64"), variable("t", "Tempo", "s", "10")],
    usageCount: 67,
    example: "12000 pacotes de 64 B em 10 s geram 614400 bit/s.",
    simpleExplanation: "Converte volume de pacotes em bits por segundo.",
    tags: ["rede", "throughput", "ethernet"],
  },
  {
    id: "tempo-resposta-automacao",
    name: "Tempo de Resposta de Automacao",
    sectorId: "automacao",
    expression: "Tr = Tentrada + Tprocesso + Tsaida",
    resultUnit: "ms",
    description: "Soma atrasos de entrada, processamento e saida do sistema.",
    variables: [
      variable("Tentrada", "Atraso de entrada", "ms", "8"),
      variable("Tprocesso", "Processamento", "ms", "20"),
      variable("Tsaida", "Atraso de saida", "ms", "12"),
    ],
    usageCount: 61,
    example: "8 + 20 + 12 resultam em 40 ms.",
    simpleExplanation: "Tempo de resposta total inclui todos os atrasos da malha.",
    tags: ["resposta", "io", "controle"],
  },
  {
    id: "disponibilidade-sistema-automacao",
    name: "Disponibilidade de Sistema",
    sectorId: "automacao",
    expression: "A = MTBF / (MTBF + MTTR) * 100",
    resultUnit: "%",
    description: "Calcula disponibilidade esperada por confiabilidade e reparo.",
    variables: [variable("MTBF", "Tempo medio entre falhas", "h", "1200"), variable("MTTR", "Tempo medio de reparo", "h", "4")],
    usageCount: 56,
    example: "MTBF = 1200 h e MTTR = 4 h geram 99.67%.",
    simpleExplanation: "Disponibilidade melhora com falhas raras e reparos rapidos.",
    tags: ["disponibilidade", "sistema", "mtbf"],
  },
  {
    id: "taxa-atualizacao",
    name: "Taxa de Atualizacao",
    sectorId: "automacao",
    expression: "F = 1 / T",
    resultUnit: "Hz",
    description: "Converte periodo de atualizacao em frequencia.",
    variables: [variable("T", "Periodo", "s", "0.02")],
    difficulty: "Basica",
    usageCount: 45,
    example: "T = 0.02 s gera 50 Hz.",
    simpleExplanation: "Frequencia e quantas atualizacoes ocorrem por segundo.",
    tags: ["frequencia", "periodo", "amostragem"],
  },
  {
    id: "buffer-comunicacao",
    name: "Buffer Necessario",
    sectorId: "automacao",
    expression: "B = Rin * Latencia",
    resultUnit: "itens",
    description: "Estima quantidade de itens que devem caber no buffer durante latencia.",
    variables: [variable("Rin", "Taxa de entrada", "itens/s", "120"), variable("Latencia", "Latencia", "s", "0.8")],
    usageCount: 39,
    example: "120 itens/s por 0.8 s pedem buffer de 96 itens.",
    simpleExplanation: "Buffer cobre o volume que chega enquanto o sistema responde.",
    tags: ["buffer", "rede", "latencia"],
  },
  {
    id: "capacidade-io",
    name: "Capacidade Total de I/O",
    sectorId: "automacao",
    expression: "IO = DI + DO + AI + AO",
    resultUnit: "pontos",
    description: "Soma pontos digitais e analogicos de um painel ou PLC.",
    variables: [
      variable("DI", "Entradas digitais", "pontos", "64"),
      variable("DO", "Saidas digitais", "pontos", "48"),
      variable("AI", "Entradas analogicas", "pontos", "16"),
      variable("AO", "Saidas analogicas", "pontos", "8"),
    ],
    difficulty: "Basica",
    usageCount: 51,
    example: "64 + 48 + 16 + 8 resultam em 136 pontos.",
    simpleExplanation: "Ajuda a verificar capacidade e expansao de I/O.",
    tags: ["io", "plc", "painel"],
  },
  {
    id: "erro-controle",
    name: "Erro de Controle",
    sectorId: "automacao",
    expression: "erro = SP - PV",
    resultUnit: "un",
    description: "Calcula diferenca instantanea entre setpoint e valor de processo.",
    variables: [variable("SP", "Setpoint", "un", "80"), variable("PV", "Valor de processo", "un", "74")],
    difficulty: "Basica",
    usageCount: 73,
    example: "SP = 80 e PV = 74 geram erro de 6.",
    simpleExplanation: "Erro positivo indica que o processo esta abaixo do alvo.",
    tags: ["pid", "erro", "controle"],
  },
  {
    id: "mtbf",
    name: "MTBF",
    sectorId: "manutencao",
    expression: "MTBF = Toper / Falhas",
    resultUnit: "h",
    description: "Calcula tempo medio entre falhas de um ativo.",
    variables: [variable("Toper", "Tempo operacional", "h", "2400"), variable("Falhas", "Numero de falhas", "un", "6")],
    usageCount: 101,
    example: "2400 h com 6 falhas geram MTBF de 400 h.",
    simpleExplanation: "Quanto maior o MTBF, menos frequentes sao as falhas.",
    tags: ["mtbf", "confiabilidade", "ativo"],
  },
  {
    id: "mttr",
    name: "MTTR",
    sectorId: "manutencao",
    expression: "MTTR = Tparado / Reparos",
    resultUnit: "h",
    description: "Calcula tempo medio necessario para reparar um ativo.",
    variables: [variable("Tparado", "Tempo parado", "h", "18"), variable("Reparos", "Reparos", "un", "6")],
    usageCount: 98,
    example: "18 h de parada em 6 reparos geram MTTR de 3 h.",
    simpleExplanation: "MTTR menor indica reparos mais rapidos.",
    tags: ["mttr", "reparo", "parada"],
  },
  {
    id: "disponibilidade-manutencao",
    name: "Disponibilidade Operacional",
    sectorId: "manutencao",
    expression: "A = MTBF / (MTBF + MTTR) * 100",
    resultUnit: "%",
    description: "Calcula disponibilidade a partir de MTBF e MTTR.",
    variables: [variable("MTBF", "MTBF", "h", "400"), variable("MTTR", "MTTR", "h", "3")],
    usageCount: 96,
    example: "MTBF 400 h e MTTR 3 h geram 99.26%.",
    simpleExplanation: "Falhas raras e reparos curtos mantem ativo disponivel.",
    tags: ["disponibilidade", "mtbf", "mttr"],
  },
  {
    id: "taxa-falha",
    name: "Taxa de Falha",
    sectorId: "manutencao",
    expression: "lambda = Falhas / Toper",
    resultUnit: "falhas/h",
    description: "Calcula frequencia media de falhas por hora operacional.",
    variables: [variable("Falhas", "Falhas", "un", "6"), variable("Toper", "Tempo operacional", "h", "2400")],
    usageCount: 69,
    example: "6 falhas em 2400 h geram 0.0025 falhas/h.",
    simpleExplanation: "Taxa de falha e o inverso aproximado da confiabilidade temporal.",
    tags: ["falha", "lambda", "confiabilidade"],
  },
  {
    id: "confiabilidade-exponencial",
    name: "Confiabilidade Exponencial",
    sectorId: "manutencao",
    expression: "R = exp(-lambda * t) * 100",
    resultUnit: "%",
    description: "Estima probabilidade de operar sem falha em um periodo.",
    variables: [variable("lambda", "Taxa de falha", "1/h", "0.0025"), variable("t", "Periodo", "h", "100")],
    difficulty: "Avancada",
    usageCount: 54,
    example: "lambda = 0.0025 e t = 100 h geram 77.88%.",
    simpleExplanation: "Quanto maior o tempo ou taxa de falha, menor a confiabilidade.",
    tags: ["confiabilidade", "exponencial", "risco"],
  },
  {
    id: "backlog-manutencao",
    name: "Backlog de Manutencao",
    sectorId: "manutencao",
    expression: "B = OSabertas / OSfechadas",
    resultUnit: "",
    description: "Compara ordens abertas com capacidade recente de fechamento.",
    variables: [variable("OSabertas", "OS abertas", "un", "45"), variable("OSfechadas", "OS fechadas no periodo", "un", "30")],
    usageCount: 65,
    example: "45 abertas e 30 fechadas geram backlog relativo de 1.5.",
    simpleExplanation: "Backlog alto indica acumulacao de trabalho pendente.",
    tags: ["backlog", "os", "planejamento"],
  },
  {
    id: "custo-hora-manutencao",
    name: "Custo por Hora Operacional",
    sectorId: "manutencao",
    expression: "C = Ctotal / Hoper",
    resultUnit: "R$/h",
    description: "Rateia custo de manutencao pelas horas de operacao do ativo.",
    variables: [variable("Ctotal", "Custo total", "R$", "18000"), variable("Hoper", "Horas operadas", "h", "720")],
    usageCount: 48,
    example: "R$ 18000 em 720 h geram R$ 25/h.",
    simpleExplanation: "Ajuda a comparar custo de manutencao por disponibilidade produtiva.",
    tags: ["custo", "hora", "ativo"],
  },
  {
    id: "indice-preventiva",
    name: "Indice de Preventivas",
    sectorId: "manutencao",
    expression: "IP = Preventivas / TotalOS * 100",
    resultUnit: "%",
    description: "Calcula participacao de manutencoes preventivas no total de ordens.",
    variables: [variable("Preventivas", "OS preventivas", "un", "42"), variable("TotalOS", "Total de OS", "un", "70")],
    usageCount: 59,
    example: "42 preventivas em 70 OS geram 60%.",
    simpleExplanation: "Percentual maior sugere manutencao mais planejada.",
    tags: ["preventiva", "os", "indicador"],
  },
  {
    id: "vida-remanescente",
    name: "Vida Remanescente",
    sectorId: "manutencao",
    expression: "VR = VidaProj - Huso",
    resultUnit: "h",
    description: "Calcula horas restantes ate a vida projetada do componente.",
    variables: [variable("VidaProj", "Vida projetada", "h", "10000"), variable("Huso", "Horas de uso", "h", "6400")],
    usageCount: 46,
    example: "10000 h projetadas e 6400 h usadas deixam 3600 h.",
    simpleExplanation: "Ajuda a programar substituicoes antes da falha.",
    tags: ["vida", "componente", "substituicao"],
  },
  {
    id: "giro-estoque",
    name: "Giro de Estoque",
    sectorId: "logistica",
    expression: "G = Consumo / EstoqueMedio",
    resultUnit: "vezes",
    description: "Calcula quantas vezes o estoque medio e consumido no periodo.",
    variables: [variable("Consumo", "Consumo no periodo", "un", "12000"), variable("EstoqueMedio", "Estoque medio", "un", "3000")],
    usageCount: 58,
    example: "Consumo 12000 e estoque medio 3000 geram giro 4.",
    simpleExplanation: "Giro maior indica estoque renovando mais rapido.",
    tags: ["estoque", "giro", "almoxarifado"],
  },
  {
    id: "cobertura-estoque",
    name: "Cobertura de Estoque",
    sectorId: "logistica",
    expression: "C = Estoque / ConsumoDia",
    resultUnit: "dias",
    description: "Calcula por quantos dias o estoque atual atende o consumo medio.",
    variables: [variable("Estoque", "Estoque atual", "un", "4500"), variable("ConsumoDia", "Consumo diario", "un/dia", "300")],
    usageCount: 55,
    example: "4500 unidades com consumo de 300/dia cobrem 15 dias.",
    simpleExplanation: "Indica autonomia de estoque antes de ruptura.",
    tags: ["cobertura", "estoque", "dias"],
  },
  {
    id: "lead-time-suprimento",
    name: "Lead Time de Suprimento",
    sectorId: "logistica",
    expression: "LT = Tp + Tc + Tr",
    resultUnit: "dias",
    description: "Soma pedido, compra e recebimento para obter prazo de suprimento.",
    variables: [variable("Tp", "Tempo de pedido", "dias", "1"), variable("Tc", "Tempo de compra", "dias", "5"), variable("Tr", "Tempo de recebimento", "dias", "2")],
    usageCount: 49,
    example: "1 + 5 + 2 geram 8 dias.",
    simpleExplanation: "Lead time completo considera todo o caminho ate o item estar disponivel.",
    tags: ["lead time", "compras", "suprimento"],
  },
  {
    id: "ocupacao-armazem",
    name: "Ocupacao de Armazem",
    sectorId: "logistica",
    expression: "O = VolumeUsado / VolumeTotal * 100",
    resultUnit: "%",
    description: "Calcula percentual de volume logistico ocupado.",
    variables: [variable("VolumeUsado", "Volume usado", "m3", "820"), variable("VolumeTotal", "Volume total", "m3", "1200")],
    usageCount: 51,
    example: "820 m3 de 1200 m3 resultam em 68.33%.",
    simpleExplanation: "Ajuda a ver folga ou saturacao do armazem.",
    tags: ["armazem", "ocupacao", "volume"],
  },
  {
    id: "custo-frete-unitario",
    name: "Custo de Frete Unitario",
    sectorId: "logistica",
    expression: "C = Cfrete / Qtd",
    resultUnit: "R$/un",
    description: "Rateia o custo de transporte por unidade movimentada.",
    variables: [variable("Cfrete", "Custo do frete", "R$", "2400"), variable("Qtd", "Quantidade", "un", "600")],
    usageCount: 38,
    example: "R$ 2400 para 600 unidades geram R$ 4/un.",
    simpleExplanation: "Permite comparar opcoes de transporte por unidade.",
    tags: ["frete", "custo", "transporte"],
  },
  {
    id: "produtividade-picking",
    name: "Produtividade de Picking",
    sectorId: "logistica",
    expression: "P = Itens / Horas",
    resultUnit: "itens/h",
    description: "Calcula itens separados por hora de trabalho.",
    variables: [variable("Itens", "Itens separados", "un", "1800"), variable("Horas", "Horas", "h", "9")],
    usageCount: 42,
    example: "1800 itens em 9 h geram 200 itens/h.",
    simpleExplanation: "Mostra velocidade operacional de separacao.",
    tags: ["picking", "produtividade", "separacao"],
  },
  {
    id: "nivel-servico-entrega",
    name: "Nivel de Servico de Entrega",
    sectorId: "logistica",
    expression: "NS = EntregasNoPrazo / Entregas * 100",
    resultUnit: "%",
    description: "Calcula percentual de entregas realizadas dentro do prazo.",
    variables: [variable("EntregasNoPrazo", "Entregas no prazo", "un", "186"), variable("Entregas", "Entregas totais", "un", "200")],
    usageCount: 57,
    example: "186 no prazo em 200 entregas geram 93%.",
    simpleExplanation: "Nivel de servico mede confiabilidade de atendimento.",
    tags: ["servico", "entrega", "sla"],
  },
  {
    id: "lote-economico",
    name: "Lote Economico de Compra",
    sectorId: "logistica",
    expression: "LE = sqrt(2 * D * S / H)",
    resultUnit: "un",
    description: "Calcula lote economico equilibrando custo de pedido e estoque.",
    variables: [variable("D", "Demanda anual", "un", "24000"), variable("S", "Custo por pedido", "R$", "180"), variable("H", "Custo de armazenagem", "R$/un.ano", "6")],
    difficulty: "Avancada",
    usageCount: 44,
    example: "D = 24000, S = 180 e H = 6 geram lote de 1200 un.",
    simpleExplanation: "Equilibra comprar muitas vezes com manter estoque alto.",
    tags: ["eoq", "compra", "estoque"],
  },
  {
    id: "cp-processo",
    name: "Cp do Processo",
    sectorId: "qualidade",
    expression: "Cp = (USL - LSL) / (6 * sigma)",
    resultUnit: "",
    description: "Mede capacidade potencial do processo pela variabilidade.",
    variables: [variable("USL", "Limite superior", "un", "10.2"), variable("LSL", "Limite inferior", "un", "9.8"), variable("sigma", "Desvio padrao", "un", "0.05")],
    usageCount: 88,
    example: "Faixa 0.4 e sigma 0.05 geram Cp = 1.33.",
    simpleExplanation: "Cp alto indica que a variacao cabe melhor dentro da especificacao.",
    tags: ["cp", "capabilidade", "qualidade"],
  },
  {
    id: "cpk-processo",
    name: "Cpk do Processo",
    sectorId: "qualidade",
    expression: "Cpk = min((USL - media) / (3 * sigma), (media - LSL) / (3 * sigma))",
    resultUnit: "",
    description: "Mede capacidade considerando variabilidade e centralizacao.",
    variables: [
      variable("USL", "Limite superior", "un", "10.2"),
      variable("LSL", "Limite inferior", "un", "9.8"),
      variable("media", "Media do processo", "un", "10.02"),
      variable("sigma", "Desvio padrao", "un", "0.05"),
    ],
    difficulty: "Avancada",
    usageCount: 84,
    example: "Processo descentralizado reduz Cpk mesmo com Cp adequado.",
    simpleExplanation: "Cpk usa o lado mais critico entre media e limites.",
    tags: ["cpk", "capabilidade", "processo"],
  },
  {
    id: "ppm-defeitos",
    name: "PPM de Defeitos",
    sectorId: "qualidade",
    expression: "PPM = Defeitos / Unidades * 1000000",
    resultUnit: "ppm",
    description: "Calcula defeitos por milhao de unidades produzidas.",
    variables: [variable("Defeitos", "Defeitos", "un", "12"), variable("Unidades", "Unidades inspecionadas", "un", "50000")],
    usageCount: 76,
    example: "12 defeitos em 50000 unidades geram 240 ppm.",
    simpleExplanation: "PPM permite comparar qualidade mesmo com volumes diferentes.",
    tags: ["ppm", "defeitos", "indicador"],
  },
  {
    id: "rendimento-qualidade",
    name: "Rendimento de Qualidade",
    sectorId: "qualidade",
    expression: "Y = Boas / Total * 100",
    resultUnit: "%",
    description: "Calcula percentual de unidades boas no total avaliado.",
    variables: [variable("Boas", "Unidades boas", "un", "980"), variable("Total", "Total produzido", "un", "1000")],
    usageCount: 74,
    example: "980 boas em 1000 unidades geram 98%.",
    simpleExplanation: "Mostra quanto da producao saiu conforme.",
    tags: ["yield", "rendimento", "boas"],
  },
  {
    id: "dpu",
    name: "Defeitos por Unidade",
    sectorId: "qualidade",
    expression: "DPU = Defeitos / Unidades",
    resultUnit: "def/un",
    description: "Calcula media de defeitos por unidade inspecionada.",
    variables: [variable("Defeitos", "Defeitos encontrados", "un", "48"), variable("Unidades", "Unidades", "un", "1200")],
    usageCount: 46,
    example: "48 defeitos em 1200 unidades geram 0.04 def/un.",
    simpleExplanation: "DPU foca quantidade de defeitos, nao apenas pecas ruins.",
    tags: ["dpu", "defeitos", "inspecao"],
  },
  {
    id: "dpmo",
    name: "DPMO",
    sectorId: "qualidade",
    expression: "DPMO = Defeitos / (Unidades * Oportunidades) * 1000000",
    resultUnit: "dpmo",
    description: "Calcula defeitos por milhao de oportunidades.",
    variables: [
      variable("Defeitos", "Defeitos", "un", "36"),
      variable("Unidades", "Unidades", "un", "1000"),
      variable("Oportunidades", "Oportunidades por unidade", "un", "5"),
    ],
    difficulty: "Avancada",
    usageCount: 43,
    example: "36 defeitos em 5000 oportunidades geram 7200 DPMO.",
    simpleExplanation: "DPMO considera quantas chances de defeito cada unidade tinha.",
    tags: ["dpmo", "seis sigma", "defeitos"],
  },
  {
    id: "z-especificacao",
    name: "Z ate Especificacao Superior",
    sectorId: "qualidade",
    expression: "Z = (USL - media) / sigma",
    resultUnit: "sigma",
    description: "Calcula distancia entre media e limite superior em desvios padrao.",
    variables: [variable("USL", "Limite superior", "un", "10.2"), variable("media", "Media", "un", "10.02"), variable("sigma", "Desvio padrao", "un", "0.05")],
    usageCount: 39,
    example: "USL 10.2, media 10.02 e sigma 0.05 geram Z = 3.6.",
    simpleExplanation: "Quanto maior o Z, mais longe a media esta do limite.",
    tags: ["z", "sigma", "limite"],
  },
  {
    id: "taxa-retrabalho",
    name: "Taxa de Retrabalho",
    sectorId: "qualidade",
    expression: "R = Retrabalho / Total * 100",
    resultUnit: "%",
    description: "Calcula percentual de unidades que precisaram retrabalho.",
    variables: [variable("Retrabalho", "Unidades retrabalhadas", "un", "35"), variable("Total", "Unidades totais", "un", "1000")],
    usageCount: 50,
    example: "35 retrabalhos em 1000 unidades geram 3.5%.",
    simpleExplanation: "Retrabalho alto consome capacidade e mascara problemas de processo.",
    tags: ["retrabalho", "perda", "qualidade"],
  },
  {
    id: "carga-maquina",
    name: "Carga Maquina",
    sectorId: "planejamento",
    expression: "Carga = TC * Qtd",
    resultUnit: "h",
    description: "Calcula horas de maquina necessarias para uma quantidade planejada.",
    variables: [variable("TC", "Tempo de ciclo", "h/un", "0.08"), variable("Qtd", "Quantidade", "un", "1200")],
    usageCount: 69,
    example: "0.08 h/un para 1200 unidades exige 96 h.",
    simpleExplanation: "Multiplica tempo unitario pela quantidade a produzir.",
    tags: ["carga", "maquina", "capacidade"],
  },
  {
    id: "ocupacao-capacidade",
    name: "Ocupacao de Capacidade",
    sectorId: "planejamento",
    expression: "O = Carga / Disponivel * 100",
    resultUnit: "%",
    description: "Compara carga planejada com horas disponiveis.",
    variables: [variable("Carga", "Carga planejada", "h", "96"), variable("Disponivel", "Capacidade disponivel", "h", "120")],
    usageCount: 66,
    example: "96 h de carga em 120 h disponiveis ocupam 80%.",
    simpleExplanation: "Ajuda a visualizar folga ou gargalo de capacidade.",
    tags: ["capacidade", "ocupacao", "planejamento"],
  },
  {
    id: "prazo-producao",
    name: "Prazo de Producao",
    sectorId: "planejamento",
    expression: "Prazo = Qtd / Taxa",
    resultUnit: "h",
    description: "Estima tempo para concluir quantidade pela taxa produtiva.",
    variables: [variable("Qtd", "Quantidade", "un", "2400"), variable("Taxa", "Taxa de producao", "un/h", "120")],
    usageCount: 57,
    example: "2400 unidades a 120 un/h levam 20 h.",
    simpleExplanation: "Divide o volume pela velocidade de producao.",
    tags: ["prazo", "taxa", "ordem"],
  },
  {
    id: "folga-atividade",
    name: "Folga de Atividade",
    sectorId: "planejamento",
    expression: "Folga = LF - EF",
    resultUnit: "dias",
    description: "Calcula folga entre termino tarde e termino cedo.",
    variables: [variable("LF", "Late finish", "dias", "18"), variable("EF", "Early finish", "dias", "15")],
    usageCount: 34,
    example: "LF = 18 e EF = 15 geram 3 dias de folga.",
    simpleExplanation: "Folga mostra atraso permitido antes de impactar o cronograma.",
    tags: ["cronograma", "folga", "cpm"],
  },
  {
    id: "cpi-evm",
    name: "CPI do Valor Agregado",
    sectorId: "planejamento",
    expression: "CPI = EV / AC",
    resultUnit: "",
    description: "Mede eficiencia de custo no gerenciamento de projeto.",
    variables: [variable("EV", "Valor agregado", "R$", "85000"), variable("AC", "Custo real", "R$", "92000")],
    usageCount: 38,
    example: "EV = 85000 e AC = 92000 geram CPI = 0.924.",
    simpleExplanation: "CPI abaixo de 1 indica custo acima do valor entregue.",
    tags: ["evm", "cpi", "projeto"],
  },
  {
    id: "spi-evm",
    name: "SPI do Valor Agregado",
    sectorId: "planejamento",
    expression: "SPI = EV / PV",
    resultUnit: "",
    description: "Mede desempenho de prazo pelo valor agregado.",
    variables: [variable("EV", "Valor agregado", "R$", "85000"), variable("PV", "Valor planejado", "R$", "100000")],
    usageCount: 37,
    example: "EV = 85000 e PV = 100000 geram SPI = 0.85.",
    simpleExplanation: "SPI abaixo de 1 sugere atraso em relacao ao plano.",
    tags: ["evm", "spi", "prazo"],
  },
  {
    id: "necessidade-material",
    name: "Necessidade de Material",
    sectorId: "planejamento",
    expression: "NM = Demanda * Consumo * (1 + Perda / 100)",
    resultUnit: "un",
    description: "Calcula material necessario considerando perda percentual.",
    variables: [variable("Demanda", "Demanda", "un", "1000"), variable("Consumo", "Consumo por unidade", "un/un", "2.5"), variable("Perda", "Perda prevista", "%", "4")],
    usageCount: 62,
    example: "1000 unidades, consumo 2.5 e perda 4% pedem 2600 un.",
    simpleExplanation: "Inclui margem de perda para evitar falta de material.",
    tags: ["mrp", "material", "perda"],
  },
  {
    id: "estoque-seguranca",
    name: "Estoque de Seguranca",
    sectorId: "planejamento",
    expression: "ES = Z * sigmaD * sqrt(LT)",
    resultUnit: "un",
    description: "Calcula estoque de seguranca por variabilidade de demanda e lead time.",
    variables: [variable("Z", "Nivel de servico Z", "", "1.65"), variable("sigmaD", "Desvio da demanda diaria", "un/dia", "35"), variable("LT", "Lead time", "dias", "9")],
    difficulty: "Avancada",
    usageCount: 54,
    example: "Z 1.65, sigma 35 e LT 9 geram 173.25 unidades.",
    simpleExplanation: "Maior incerteza ou lead time exige mais protecao de estoque.",
    tags: ["estoque", "seguranca", "demanda"],
  },
  {
    id: "fator-carga",
    name: "Fator de Carga",
    sectorId: "energia",
    expression: "FC = E / (Pmax * t) * 100",
    resultUnit: "%",
    description: "Compara energia consumida com uso continuo da demanda maxima.",
    variables: [variable("E", "Energia consumida", "kWh", "42000"), variable("Pmax", "Demanda maxima", "kW", "180"), variable("t", "Periodo", "h", "720")],
    usageCount: 97,
    example: "42000 kWh, 180 kW e 720 h geram 32.4%.",
    simpleExplanation: "Fator de carga alto indica uso mais uniforme da demanda.",
    tags: ["demanda", "energia", "fator carga"],
  },
  {
    id: "custo-energia",
    name: "Custo de Energia",
    sectorId: "energia",
    expression: "C = CkWh * E",
    resultUnit: "R$",
    description: "Calcula custo direto de energia pelo consumo e tarifa.",
    variables: [variable("CkWh", "Tarifa", "R$/kWh", "0.72"), variable("E", "Consumo", "kWh", "42000")],
    usageCount: 92,
    example: "42000 kWh a R$ 0.72 custam R$ 30240.",
    simpleExplanation: "Multiplica consumo faturado pela tarifa de energia.",
    tags: ["custo", "energia", "tarifa"],
  },
  {
    id: "demanda-contratada",
    name: "Demanda Contratada Recomendada",
    sectorId: "energia",
    expression: "D = Pponta * Fsim",
    resultUnit: "kW",
    description: "Estima demanda contratada a partir do pico e fator de simultaneidade.",
    variables: [variable("Pponta", "Potencia de ponta", "kW", "260"), variable("Fsim", "Fator de simultaneidade", "", "0.82")],
    usageCount: 61,
    example: "260 kW com fator 0.82 sugerem 213.2 kW.",
    simpleExplanation: "Nem todas as cargas operam juntas; o fator corrige o pico instalado.",
    tags: ["demanda", "contrato", "ponta"],
  },
  {
    id: "economia-anual-energia",
    name: "Economia Anual de Energia",
    sectorId: "energia",
    expression: "Eco = (Ebase - Eatual) * CkWh",
    resultUnit: "R$/ano",
    description: "Calcula economia financeira por reducao de consumo.",
    variables: [variable("Ebase", "Consumo base", "kWh/ano", "640000"), variable("Eatual", "Consumo atual", "kWh/ano", "560000"), variable("CkWh", "Tarifa", "R$/kWh", "0.72")],
    usageCount: 69,
    example: "Reducao de 80000 kWh a R$ 0.72 economiza R$ 57600/ano.",
    simpleExplanation: "Transforma economia de kWh em dinheiro anual.",
    tags: ["economia", "eficiencia", "energia"],
  },
  {
    id: "intensidade-energetica",
    name: "Intensidade Energetica",
    sectorId: "energia",
    expression: "IE = E / Producao",
    resultUnit: "kWh/un",
    description: "Calcula energia consumida por unidade produzida.",
    variables: [variable("E", "Energia consumida", "kWh", "42000"), variable("Producao", "Producao", "un", "21000")],
    usageCount: 73,
    example: "42000 kWh para 21000 unidades geram 2 kWh/un.",
    simpleExplanation: "Permite comparar eficiencia energetica entre turnos ou produtos.",
    tags: ["intensidade", "producao", "kwh"],
  },
  {
    id: "fator-potencia",
    name: "Fator de Potencia",
    sectorId: "energia",
    expression: "FP = P / S",
    resultUnit: "",
    description: "Calcula relacao entre potencia ativa e aparente.",
    variables: [variable("P", "Potencia ativa", "kW", "180"), variable("S", "Potencia aparente", "kVA", "205")],
    usageCount: 81,
    example: "P = 180 kW e S = 205 kVA geram FP = 0.878.",
    simpleExplanation: "FP proximo de 1 indica melhor aproveitamento da energia aparente.",
    tags: ["fp", "energia", "reativo"],
  },
  {
    id: "emissao-co2",
    name: "Emissao de CO2",
    sectorId: "energia",
    expression: "CO2 = E * FE",
    resultUnit: "kgCO2",
    description: "Estima emissao associada ao consumo de energia.",
    variables: [variable("E", "Energia", "kWh", "42000"), variable("FE", "Fator de emissao", "kgCO2/kWh", "0.081")],
    usageCount: 44,
    example: "42000 kWh com FE 0.081 geram 3402 kgCO2.",
    simpleExplanation: "Transforma consumo de energia em impacto ambiental estimado.",
    tags: ["co2", "sustentabilidade", "emissao"],
  },
  {
    id: "payback-energia",
    name: "Payback de Projeto Energetico",
    sectorId: "energia",
    expression: "PB = Investimento / EconomiaAnual",
    resultUnit: "anos",
    description: "Calcula tempo simples de retorno de investimento energetico.",
    variables: [variable("Investimento", "Investimento", "R$", "180000"), variable("EconomiaAnual", "Economia anual", "R$/ano", "57600")],
    usageCount: 66,
    example: "R$ 180000 com economia R$ 57600/ano retornam em 3.13 anos.",
    simpleExplanation: "Mostra em quantos anos a economia paga o investimento.",
    tags: ["payback", "projeto", "energia"],
  },
];

const mistura90FormulaSeeds: FormulaSeed[] = [
  {
    id: "mistura90-capacidade-elevador",
    name: "Capacidade do Elevador",
    sectorId: "elevadores_mistura_90",
    expression: "Q = (3600 * V * n * v * CF1 * CF2 * gamma) / e",
    resultUnit: "m3/h",
    description: "Calcula a capacidade volumetrica/produtiva do elevador por volume de caneca, fileiras, velocidade e fatores de enchimento.",
    variables: [
      variable("V", "Volume da caneca", "m3", "0.008"),
      variable("n", "Numero de fileiras", "fileiras", "2"),
      variable("v", "Velocidade da correia/corrente", "m/s", "1.2"),
      variable("CF1", "Coeficiente de enchimento", "", "0.75"),
      variable("CF2", "Coeficiente de homogeneidade", "", "0.9"),
      variable("gamma", "Peso especifico do material", "t/m3", "0.85"),
      variable("e", "Passo das canecas", "m", "0.305"),
    ],
    usageCount: 88,
    example: "V=0.008, n=2, v=1.2, CF1=0.75, CF2=0.9, gamma=0.85 e e=0.305 geram a capacidade em m3/h.",
    simpleExplanation: "A capacidade cresce com canecas maiores, mais fileiras e maior velocidade, corrigida pelos coeficientes do material.",
    tags: ["mistura 90", "elevador", "capacidade", "canecas"],
    technicalNotes: "Baseado no calculo de capacidade do elevador do documento Calculos Equipamentos Mistura 90.",
  },
  {
    id: "mistura90-peso-metro-material",
    name: "Peso por Metro de Material",
    sectorId: "elevadores_mistura_90",
    expression: "Pm = (1000 * n * gamma * V) / e",
    resultUnit: "kg/m",
    description: "Calcula o peso de material transportado por metro do elevador.",
    variables: [variable("n", "Numero de fileiras", "fileiras", "2"), variable("gamma", "Peso especifico do material", "t/m3", "0.85"), variable("V", "Volume da caneca", "m3", "0.008"), variable("e", "Passo das canecas", "m", "0.305")],
    usageCount: 82,
    example: "Com duas fileiras, gamma=0.85 t/m3, V=0.008 m3 e e=0.305 m, o sistema estima kg de material por metro.",
    simpleExplanation: "Transforma o volume das canecas e densidade do material em carga distribuida por metro.",
    tags: ["mistura 90", "peso", "material"],
  },
  {
    id: "mistura90-comprimento-correia-aberta",
    name: "Comprimento da Correia ou Corrente Aberta",
    sectorId: "elevadores_mistura_90",
    expression: "Ca = pi * D + 2 * H",
    resultUnit: "m",
    description: "Estima o comprimento aberto da correia ou corrente considerando tambor e altura entre centros.",
    variables: [variable("D", "Diametro do tambor", "m", "0.42"), variable("H", "Altura entre centros", "m", "18")],
    usageCount: 80,
    example: "D=0.42 m e H=18 m resultam em comprimento aberto aproximado da correia.",
    simpleExplanation: "Soma duas pernas verticais com o contorno do tambor.",
    tags: ["mistura 90", "correia", "corrente"],
  },
  {
    id: "mistura90-numero-canecas",
    name: "Numero de Canecas",
    sectorId: "elevadores_mistura_90",
    expression: "N1 = (1000 * Ca * n) / e",
    resultUnit: "canecas",
    description: "Calcula a quantidade aproximada de canecas montadas na correia ou corrente.",
    variables: [variable("Ca", "Comprimento aberto", "m", "37.3"), variable("n", "Numero de fileiras", "fileiras", "2"), variable("e", "Passo das canecas", "mm", "305")],
    usageCount: 79,
    example: "Ca=37.3 m, n=2 e e=305 mm geram a quantidade de canecas instaladas.",
    simpleExplanation: "Divide o comprimento total pelo passo e multiplica pelo numero de fileiras.",
    tags: ["mistura 90", "canecas", "passo"],
  },
  {
    id: "mistura90-tensao-estatica",
    name: "Tensao Estatica",
    sectorId: "elevadores_mistura_90",
    expression: "Tp = (p * N1) / 2 + (pc * Ca) / 4 + (p1 * N1) / 4",
    resultUnit: "kgf",
    description: "Calcula a tensao estatica combinando peso de canecas, correia/corrente e carga transportada.",
    variables: [variable("p", "Peso unitario da caneca", "kgf", "3.2"), variable("N1", "Numero de canecas", "canecas", "245"), variable("pc", "Peso da correia/corrente", "kgf/m", "8.5"), variable("Ca", "Comprimento aberto", "m", "37.3"), variable("p1", "Peso de material por caneca", "kgf", "5.4")],
    usageCount: 75,
    example: "Com pesos unitarios e comprimento aberto, a formula estima a tensao estatica total.",
    simpleExplanation: "Reune as parcelas permanentes que tracionam o sistema parado.",
    tags: ["mistura 90", "tensao", "estatica"],
  },
  {
    id: "mistura90-tensao-efetiva-carga",
    name: "Tensao Efetiva por Carga",
    sectorId: "elevadores_mistura_90",
    expression: "Te = ((H + 12 * D) * p1) / e",
    resultUnit: "kgf",
    description: "Calcula tensao efetiva pela carga elevada e parcela adicional associada ao tambor.",
    variables: [variable("H", "Altura de elevacao", "m", "18"), variable("D", "Diametro do tambor", "m", "0.42"), variable("p1", "Peso de material por caneca", "kgf", "5.4"), variable("e", "Passo das canecas", "m", "0.305")],
    usageCount: 72,
    example: "H=18 m, D=0.42 m, p1=5.4 kgf e e=0.305 m geram tensao efetiva.",
    simpleExplanation: "Aumenta com altura, diametro de referencia e carga por caneca.",
    tags: ["mistura 90", "tensao efetiva", "carga"],
  },
  {
    id: "mistura90-tensao-efetiva-canecas",
    name: "Tensao Efetiva por Numero de Canecas",
    sectorId: "elevadores_mistura_90",
    expression: "Te = (0.8 * p1 * N * (H + Ho)) / H",
    resultUnit: "kgf",
    description: "Calcula tensao efetiva usando numero de canecas carregadas e altura equivalente.",
    variables: [variable("p1", "Peso de material por caneca", "kgf", "5.4"), variable("N", "Numero de canecas", "canecas", "245"), variable("H", "Altura de elevacao", "m", "18"), variable("Ho", "Altura complementar", "m", "1.2")],
    usageCount: 70,
    example: "p1=5.4, N=245, H=18 e Ho=1.2 fornecem tensao efetiva por canecas.",
    simpleExplanation: "Considera a fracao util de carga distribuida pelas canecas do elevador.",
    tags: ["mistura 90", "canecas", "tensao efetiva"],
  },
  {
    id: "mistura90-tensao-maxima",
    name: "Tensao Maxima",
    sectorId: "elevadores_mistura_90",
    expression: "Tm = (1 + k) * Te",
    resultUnit: "kgf",
    description: "Aplica fator dinamico sobre a tensao efetiva para obter tensao maxima de projeto.",
    variables: [variable("k", "Fator adicional/dinamico", "", "0.25"), variable("Te", "Tensao efetiva", "kgf", "1800")],
    usageCount: 76,
    example: "k=0.25 e Te=1800 kgf resultam em Tm=2250 kgf.",
    simpleExplanation: "A tensao maxima adiciona margem dinamica sobre a carga efetiva.",
    tags: ["mistura 90", "tensao maxima", "projeto"],
  },
  {
    id: "mistura90-fator-abracamento",
    name: "Fator de Abracamento do Tambor",
    sectorId: "elevadores_mistura_90",
    expression: "K = 1 / (exp(0.0174 * angulo * mi) - 1)",
    resultUnit: "",
    description: "Calcula fator de abracamento pelo angulo de contato e coeficiente de atrito.",
    variables: [variable("angulo", "Angulo de abracamento", "graus", "180"), variable("mi", "Coeficiente de atrito", "", "0.35")],
    difficulty: "Avancada",
    usageCount: 68,
    example: "angulo=180 graus e mi=0.35 resultam no fator K para o tambor.",
    simpleExplanation: "Quanto maior o contato e atrito, menor a necessidade de esticamento adicional.",
    tags: ["mistura 90", "tambor", "abracamento"],
  },
  {
    id: "mistura90-peso-esticador",
    name: "Peso do Esticador por Gravidade",
    sectorId: "elevadores_mistura_90",
    expression: "Pe = K * Te",
    resultUnit: "kgf",
    description: "Calcula o peso requerido no esticador por gravidade.",
    variables: [variable("K", "Fator de abracamento", "", "0.42"), variable("Te", "Tensao efetiva", "kgf", "1800")],
    usageCount: 64,
    example: "K=0.42 e Te=1800 kgf indicam Pe=756 kgf.",
    simpleExplanation: "O esticador precisa compensar a tensao efetiva conforme o fator de contato.",
    tags: ["mistura 90", "esticador", "gravidade"],
  },
  {
    id: "mistura90-unidade-tensao-correia",
    name: "Unidade de Tensao da Correia",
    sectorId: "elevadores_mistura_90",
    expression: "Ut = Tm / B",
    resultUnit: "kgf/cm",
    description: "Calcula tensao por unidade de largura da correia.",
    variables: [variable("Tm", "Tensao maxima", "kgf", "2250"), variable("B", "Largura da correia", "cm", "45")],
    usageCount: 66,
    example: "Tm=2250 kgf e B=45 cm resultam em 50 kgf/cm.",
    simpleExplanation: "Distribui a tensao total pela largura resistente da correia.",
    tags: ["mistura 90", "correia", "tensao"],
  },
  {
    id: "mistura90-numero-minimo-lonas",
    name: "Numero Minimo de Lonas",
    sectorId: "elevadores_mistura_90",
    expression: "Nm = Ut / Tu",
    resultUnit: "lonas",
    description: "Estima o numero minimo de lonas pela tensao unitaria e resistencia por lona.",
    variables: [variable("Ut", "Unidade de tensao", "kgf/cm", "50"), variable("Tu", "Tensao admissivel por lona", "kgf/cm", "12")],
    usageCount: 63,
    example: "Ut=50 e Tu=12 indicam necessidade minima de 4.17 lonas.",
    simpleExplanation: "Divide a tensao requerida pela capacidade de cada lona.",
    tags: ["mistura 90", "lonas", "correia"],
  },
  {
    id: "mistura90-percentual-tensao-admissivel",
    name: "Porcentagem da Tensao Admissivel",
    sectorId: "elevadores_mistura_90",
    expression: "TadPercent = (T1 * 100) / (Tu * B * NL)",
    resultUnit: "%",
    description: "Verifica quanto da tensao admissivel da correia esta sendo utilizado.",
    variables: [variable("T1", "Tensao atuante", "kgf", "2250"), variable("Tu", "Tensao admissivel por lona", "kgf/cm", "12"), variable("B", "Largura da correia", "cm", "45"), variable("NL", "Numero de lonas", "lonas", "5")],
    usageCount: 62,
    example: "T1=2250, Tu=12, B=45 e NL=5 indicam 83.33% da tensao admissivel.",
    simpleExplanation: "Compara a tensao aplicada com a capacidade total da carcaça.",
    tags: ["mistura 90", "tensao admissivel", "correia"],
  },
  {
    id: "mistura90-momento-fletor-eixo-motriz",
    name: "Momento Fletor do Eixo Motriz",
    sectorId: "elevadores_mistura_90",
    expression: "Mf = (P * a) / 2",
    resultUnit: "kgf.cm",
    description: "Calcula momento fletor no eixo motriz pela carga aplicada e braco.",
    variables: [variable("P", "Carga aplicada", "kgf", "2600"), variable("a", "Distancia entre apoio e carga", "cm", "32")],
    usageCount: 67,
    example: "P=2600 kgf e a=32 cm resultam em Mf=41600 kgf.cm.",
    simpleExplanation: "O momento cresce com a carga e com a distancia ate o apoio.",
    tags: ["mistura 90", "eixo", "momento fletor"],
  },
  {
    id: "mistura90-momento-torsor",
    name: "Momento Torsor",
    sectorId: "elevadores_mistura_90",
    expression: "Mt = (N * 38 * D) / v",
    resultUnit: "kgf.cm",
    description: "Calcula momento torsor transmitido ao eixo a partir de potencia, diametro e velocidade.",
    variables: [variable("N", "Potencia transmitida", "cv", "12.5"), variable("D", "Diametro do tambor", "m", "0.42"), variable("v", "Velocidade da correia", "m/s", "1.2")],
    usageCount: 65,
    example: "N=12.5 cv, D=0.42 m e v=1.2 m/s geram o momento torsor.",
    simpleExplanation: "Representa o esforço de torção que o eixo precisa transmitir.",
    tags: ["mistura 90", "eixo", "torcao"],
  },
  {
    id: "mistura90-momento-ideal-composto",
    name: "Momento Ideal/Composto",
    sectorId: "elevadores_mistura_90",
    expression: "Mi = sqrt((Fsf * Mf)^2 + (Fst * Mt)^2)",
    resultUnit: "kgf.cm",
    description: "Combina momento fletor e torsor com fatores de servico para dimensionar o eixo.",
    variables: [variable("Fsf", "Fator de servico a flexao", "", "1.5"), variable("Mf", "Momento fletor", "kgf.cm", "41600"), variable("Fst", "Fator de servico a torcao", "", "1.2"), variable("Mt", "Momento torsor", "kgf.cm", "166")],
    difficulty: "Avancada",
    usageCount: 61,
    example: "Com fatores de servico, Mf e Mt sao combinados por soma quadratica.",
    simpleExplanation: "Gera um momento equivalente para avaliar o eixo sob flexao e torcao juntas.",
    tags: ["mistura 90", "eixo", "momento composto"],
  },
  {
    id: "mistura90-diametro-minimo-eixo-motriz",
    name: "Diametro Minimo do Eixo Motriz",
    sectorId: "elevadores_mistura_90",
    expression: "d = cbrt((16 * Mi) / (pi * sigmaAdm))",
    resultUnit: "cm",
    description: "Dimensiona o diametro minimo do eixo motriz pelo momento composto e tensao admissivel.",
    variables: [variable("Mi", "Momento ideal/composto", "kgf.cm", "62400"), variable("sigmaAdm", "Tensao admissivel", "kgf/cm2", "850")],
    difficulty: "Avancada",
    usageCount: 60,
    example: "Mi=62400 kgf.cm e sigmaAdm=850 kgf/cm2 resultam em diametro minimo do eixo.",
    simpleExplanation: "Raiz cubica relaciona momento resistente e tensao admissivel do material.",
    tags: ["mistura 90", "eixo motriz", "diametro"],
  },
  {
    id: "mistura90-diametro-minimo-eixo-movido",
    name: "Diametro Minimo do Eixo Movido",
    sectorId: "elevadores_mistura_90",
    expression: "d = cbrt((32 * Mf * Fsf) / (pi * sigmaAdm))",
    resultUnit: "cm",
    description: "Dimensiona eixo movido considerando momento fletor e fator de servico.",
    variables: [variable("Mf", "Momento fletor", "kgf.cm", "41600"), variable("Fsf", "Fator de servico a flexao", "", "1.5"), variable("sigmaAdm", "Tensao admissivel", "kgf/cm2", "850")],
    difficulty: "Avancada",
    usageCount: 58,
    example: "Mf=41600, Fsf=1.5 e sigmaAdm=850 definem o diametro minimo.",
    simpleExplanation: "Usa flexao corrigida para estimar a seção resistente necessaria.",
    tags: ["mistura 90", "eixo movido", "diametro"],
  },
  {
    id: "mistura90-flecha-maxima-eixo",
    name: "Flecha Maxima do Eixo",
    sectorId: "elevadores_mistura_90",
    expression: "f = (4 * P * Ks * (L - C) * (2 * L^2 + 2 * L * C - C^2)) / (3 * pi * E * d^4)",
    resultUnit: "cm",
    description: "Calcula a flecha maxima do eixo para verificacao de rigidez.",
    variables: [variable("P", "Carga aplicada", "kgf", "2600"), variable("Ks", "Fator de rigidez/servico", "", "1"), variable("L", "Distancia entre apoios", "cm", "110"), variable("C", "Distancia ate carga", "cm", "32"), variable("E", "Modulo de elasticidade", "kgf/cm2", "2100000"), variable("d", "Diametro do eixo", "cm", "7")],
    difficulty: "Avancada",
    usageCount: 56,
    example: "Com carga, vao e diametro definidos, a formula calcula a deflexao maxima.",
    simpleExplanation: "A flecha cai muito quando o diametro do eixo aumenta.",
    tags: ["mistura 90", "flecha", "eixo"],
  },
  {
    id: "mistura90-potencia-motor",
    name: "Potencia do Motor",
    sectorId: "elevadores_mistura_90",
    expression: "N = (v * Pm * n * (H + 7 * D)) / (75 * eta)",
    resultUnit: "cv",
    description: "Calcula potencia requerida do motor para elevar a carga do sistema.",
    variables: [variable("v", "Velocidade da correia", "m/s", "1.2"), variable("Pm", "Peso por metro de material", "kgf/m", "44.6"), variable("n", "Numero de fileiras", "fileiras", "2"), variable("H", "Altura de elevacao", "m", "18"), variable("D", "Diametro do tambor", "m", "0.42"), variable("eta", "Rendimento global", "", "0.82")],
    usageCount: 70,
    example: "v=1.2, Pm=44.6, n=2, H=18, D=0.42 e eta=0.82 geram potencia em cv.",
    simpleExplanation: "Potencia aumenta com velocidade, peso transportado e altura de elevacao.",
    tags: ["mistura 90", "motor", "potencia"],
  },
  {
    id: "mistura90-rotacao-saida-redutor",
    name: "Rotacao de Saida do Redutor",
    sectorId: "elevadores_mistura_90",
    expression: "rs = (V * 60) / (D * pi)",
    resultUnit: "rpm",
    description: "Calcula a rotacao de saida necessaria no redutor para obter velocidade linear.",
    variables: [variable("V", "Velocidade linear", "m/s", "1.2"), variable("D", "Diametro do tambor", "m", "0.42")],
    usageCount: 64,
    example: "V=1.2 m/s e D=0.42 m geram rpm de saida do redutor.",
    simpleExplanation: "Converte velocidade da correia em rotacao do tambor.",
    tags: ["mistura 90", "redutor", "rpm"],
  },
  {
    id: "mistura90-reducao-redutor",
    name: "Reducao do Redutor",
    sectorId: "elevadores_mistura_90",
    expression: "R = Rm / rs",
    resultUnit: ":1",
    description: "Calcula relacao de reducao entre rotacao do motor e saida requerida.",
    variables: [variable("Rm", "Rotacao do motor", "rpm", "1750"), variable("rs", "Rotacao de saida", "rpm", "54.6")],
    usageCount: 62,
    example: "Rm=1750 rpm e rs=54.6 rpm indicam reducao de 32:1.",
    simpleExplanation: "Mostra quanto o redutor precisa reduzir a rotacao do motor.",
    tags: ["mistura 90", "redutor", "reducao"],
  },
  {
    id: "mistura90-momento-equivalente-acoplamento",
    name: "Momento Equivalente do Acoplamento",
    sectorId: "elevadores_mistura_90",
    expression: "Meq = (C * N * Fs) / n",
    resultUnit: "kgf.m",
    description: "Dimensiona momento equivalente para selecao de acoplamento.",
    variables: [variable("C", "Constante do acoplamento", "", "716.2"), variable("N", "Potencia", "cv", "12.5"), variable("Fs", "Fator de servico", "", "1.5"), variable("n", "Rotacao", "rpm", "54.6")],
    usageCount: 57,
    example: "C=716.2, N=12.5, Fs=1.5 e n=54.6 geram momento equivalente.",
    simpleExplanation: "Corrige o torque de trabalho para escolher um acoplamento robusto.",
    tags: ["mistura 90", "acoplamento", "momento"],
  },
  {
    id: "mistura90-capacidade-dinamica-rolamento",
    name: "Capacidade Dinamica do Rolamento",
    sectorId: "elevadores_mistura_90",
    expression: "C = P * cbrt((60 * n * L10h) / 1000000)",
    resultUnit: "N",
    description: "Calcula capacidade dinamica requerida do rolamento pela vida nominal L10h.",
    variables: [variable("P", "Carga dinamica equivalente", "N", "18000"), variable("n", "Rotacao", "rpm", "54.6"), variable("L10h", "Vida nominal", "h", "30000")],
    difficulty: "Avancada",
    usageCount: 55,
    example: "P=18000 N, n=54.6 rpm e L10h=30000 h geram a capacidade dinamica requerida.",
    simpleExplanation: "Maior carga, rotacao ou vida requerida aumentam a capacidade do rolamento.",
    tags: ["mistura 90", "rolamento", "L10h"],
  },
  {
    id: "mistura90-espessura-costado-tambor",
    name: "Espessura do Costado do Tambor",
    sectorId: "elevadores_mistura_90",
    expression: "s = sqrt((2 * Kc * 3 * P * D) / sigmaC)",
    resultUnit: "cm",
    description: "Calcula espessura minima do costado do tambor conforme carga, diametro e tensao admissivel.",
    variables: [variable("Kc", "Coeficiente do costado", "", "1.2"), variable("P", "Carga aplicada", "kgf", "2600"), variable("D", "Diametro do tambor", "cm", "42"), variable("sigmaC", "Tensao admissivel do costado", "kgf/cm2", "900")],
    difficulty: "Avancada",
    usageCount: 54,
    example: "Kc=1.2, P=2600 kgf, D=42 cm e sigmaC=900 kgf/cm2 fornecem a espessura minima.",
    simpleExplanation: "Dimensiona a chapa do tambor para resistir aos esforcos do elevador.",
    tags: ["mistura 90", "tambor", "costado"],
  },
];

const allFormulaSeeds = [...formulaSeeds, ...mistura90FormulaSeeds];

export const formulas: Formula[] = allFormulaSeeds.map((seed, index) => ({
  difficulty: "Intermediaria",
  usageCount: Math.max(18, 120 - index),
  status: "aprovada",
  createdBy: "i9TMG Engenharia",
  approvedBy: "Administrador i9TMG",
  createdAt: "2026-04-24T00:00:00.000Z",
  approvedAt: "2026-04-24T00:00:00.000Z",
  version: 1,
  ...seed,
  sector: sectorNameById[seed.sectorId],
}));

export const sectors: Sector[] = baseSectors.map((sector) => ({
  ...sector,
  formulas: formulas.filter((formula) => formula.sectorId === sector.id).length,
}));

export const calculationsHistory: CalculationRecord[] = [
  {
    id: 1007,
    formulaId: "torque",
    formula: "Torque de Aperto",
    sector: "Mecanica",
    sectorId: "mecanica",
    values: { F: "150", r: "0.30" },
    result: "45.0000",
    unit: "N.m",
    formulaStatus: "aprovada",
    status: "Validado",
    operator: "Eng. Marina",
    date: "24/04/2026 14:32",
    isoDate: "2026-04-24",
  },
  {
    id: 1006,
    formulaId: "queda-tensao-monofasica",
    formula: "Queda de Tensao Monofasica",
    sector: "Eletrica",
    sectorId: "eletrica",
    values: { I: "25", R: "0.019", L: "50" },
    result: "47.5000",
    unit: "V",
    formulaStatus: "aprovada",
    status: "Revisao",
    operator: "Tec. Bruno",
    date: "24/04/2026 11:15",
    isoDate: "2026-04-24",
  },
  {
    id: 1005,
    formulaId: "vazao-bomba",
    formula: "Vazao Volumetrica",
    sector: "Hidraulica",
    sectorId: "hidraulica",
    values: { A: "0.05", v: "2.5" },
    result: "0.1250",
    unit: "m3/s",
    formulaStatus: "aprovada",
    status: "Validado",
    operator: "Eng. Caio",
    date: "23/04/2026 16:45",
    isoDate: "2026-04-23",
  },
  {
    id: 1004,
    formulaId: "oee",
    formula: "OEE",
    sector: "Producao",
    sectorId: "producao",
    values: { D: "92", P: "95", Q: "99.5" },
    result: "87.0300",
    unit: "%",
    formulaStatus: "aprovada",
    status: "Validado",
    operator: "Coord. Paula",
    date: "23/04/2026 09:20",
    isoDate: "2026-04-23",
  },
  {
    id: 1003,
    formulaId: "carga-scan-plc",
    formula: "Carga de Scan de PLC",
    sector: "Automacao",
    sectorId: "automacao",
    values: { Tscan: "18", Tlim: "50" },
    result: "36.0000",
    unit: "%",
    formulaStatus: "aprovada",
    status: "Validado",
    operator: "Eng. Marina",
    date: "22/04/2026 15:00",
    isoDate: "2026-04-22",
  },
  {
    id: 1002,
    formulaId: "mtbf",
    formula: "MTBF",
    sector: "Manutencao",
    sectorId: "manutencao",
    values: { Toper: "2400", Falhas: "6" },
    result: "400.0000",
    unit: "h",
    formulaStatus: "aprovada",
    status: "Validado",
    operator: "Tec. Bruno",
    date: "21/04/2026 10:30",
    isoDate: "2026-04-21",
  },
  {
    id: 1001,
    formulaId: "cpk-processo",
    formula: "Cpk do Processo",
    sector: "Qualidade",
    sectorId: "qualidade",
    values: { USL: "10.2", LSL: "9.8", media: "10.02", sigma: "0.05" },
    result: "1.2000",
    unit: "",
    formulaStatus: "validada",
    status: "Revisao",
    operator: "Analista Joao",
    date: "20/04/2026 08:40",
    isoDate: "2026-04-20",
  },
];

export const weeklyActivity = [
  { day: "Seg", calculos: 18, validacoes: 12 },
  { day: "Ter", calculos: 24, validacoes: 18 },
  { day: "Qua", calculos: 31, validacoes: 22 },
  { day: "Qui", calculos: 38, validacoes: 29 },
  { day: "Sex", calculos: 42, validacoes: 34 },
  { day: "Sab", calculos: 14, validacoes: 9 },
  { day: "Dom", calculos: 8, validacoes: 5 },
];

export const sectorUsage = sectors.map((sector) => ({
  name: sector.name,
  calculos: sector.activeCalculations,
  formulas: sector.formulas,
}));

export function calculateFormula(formulaId: string, values: Record<string, string>) {
  const formula = formulas.find((item) => item.id === formulaId);
  if (!formula) {
    return Object.values(values).reduce((acc, value) => acc * Number.parseFloat(value || "1"), 1);
  }

  return evaluateFormula(formula, values);
}

export function getSectorById(sectorId: SectorId) {
  return sectors.find((sector) => sector.id === sectorId) || sectors[0];
}
